/**
 * Иконки категорий — ОДИН набор на всё приложение: Phosphor.
 *
 * DECISION владельца 2026-09-05: «иконки у каждой категории сильно
 * различаются, нужны в одном стиле — современном, как у больших компаний,
 * как у Thumbtack (наш референс)».
 *
 * Что было: три набора одновременно — цветные Twemoji, цветные Fluent и
 * линейные Lucide. На одном экране «Клининг» тонкой линией стоял рядом с
 * объёмной каплей «Сантехники». Цветные иконки к тому же грузились с
 * чужого CDN (Iconify) — сеть ради значка.
 *
 * Что стало: имя иконки из `categories_l2.icon` / `categories_l1.icon`
 * (миграция 0157 проставила всем категориям имена из Phosphor) → компонент
 * Phosphor. Линейные, одной толщины, красятся токеном темы. Референс —
 * Thumbtack: у него иконки категорий тоже линейные и одноцветные.
 *
 * Имена сверены со списком node_modules/phosphor-react-native/src/icons.
 * Запасная иконка — Wrench: если имя из базы здесь не найдено, категория
 * всё равно рисуется, а не падает.
 */

import {
  AppWindow,
  Baby,
  Balloon,
  BookOpen,
  Briefcase,
  Broadcast,
  Broom,
  Bug,
  Buildings,
  Cake,
  Calculator,
  Camera,
  Car,
  CarProfile,
  Cloud,
  Compass,
  Confetti,
  Couch,
  Crane,
  Cube,
  Desktop,
  DeviceMobile,
  Door,
  DotsThree,
  Drop,
  Engine,
  Fan,
  FilmSlate,
  Fire,
  ForkKnife,
  Garage,
  Gavel,
  Gear,
  GraduationCap,
  GridFour,
  Hammer,
  HandHeart,
  HardHat,
  Headset,
  House,
  Key,
  Keyboard,
  Laptop,
  Lightning,
  Megaphone,
  Microphone,
  Moped,
  MusicNotes,
  Package,
  PaintBrush,
  PaintBucket,
  PencilRuler,
  Phone,
  Pipe,
  Plant,
  Rows,
  Ruler,
  Scales,
  Scissors,
  SecurityCamera,
  ShieldCheck,
  ShoppingBag,
  Shovel,
  Snowflake,
  Sparkle,
  Square,
  SquaresFour,
  StackSimple,
  Television,
  Thermometer,
  Tire,
  TrafficCone,
  Translate,
  Trash,
  TreeEvergreen,
  Truck,
  VideoCamera,
  Wall,
  WashingMachine,
  Waves,
  Wrench,
} from "phosphor-react-native";
import type { IconComponent } from "@/types/icon";

export const CATEGORY_ICONS: Record<string, IconComponent> = {
  // Разделы и категории расширения каталога 0209 (2026-10-01) — тоже здесь.
  AppWindow,
  Baby,
  Balloon,
  BookOpen,
  Briefcase,
  Broadcast,
  Broom,
  Bug,
  Buildings,
  Cake,
  Calculator,
  Camera,
  Car,
  CarProfile,
  Cloud,
  Compass,
  Confetti,
  Couch,
  Crane,
  Cube,
  Desktop,
  DeviceMobile,
  Door,
  DotsThree,
  Drop,
  Engine,
  Fan,
  FilmSlate,
  Fire,
  ForkKnife,
  Garage,
  Gavel,
  Gear,
  GraduationCap,
  GridFour,
  Hammer,
  HandHeart,
  HardHat,
  Headset,
  House,
  Key,
  Keyboard,
  Laptop,
  Lightning,
  Megaphone,
  Microphone,
  Moped,
  MusicNotes,
  Package,
  PaintBrush,
  PaintBucket,
  PencilRuler,
  Phone,
  Pipe,
  Plant,
  Rows,
  Ruler,
  Scales,
  Scissors,
  SecurityCamera,
  ShieldCheck,
  ShoppingBag,
  Shovel,
  Snowflake,
  Sparkle,
  Square,
  SquaresFour,
  StackSimple,
  Television,
  Thermometer,
  Tire,
  TrafficCone,
  Translate,
  Trash,
  TreeEvergreen,
  Truck,
  VideoCamera,
  Wall,
  WashingMachine,
  Waves,
  Wrench,
};

export const DEFAULT_CATEGORY_ICON: IconComponent = Wrench;

/** Иконка по имени из базы; неизвестное имя → Wrench. */
export function getCategoryIcon(iconName: string | null | undefined): IconComponent {
  if (!iconName) return DEFAULT_CATEGORY_ICON;
  return CATEGORY_ICONS[iconName] ?? DEFAULT_CATEGORY_ICON;
}
