-- 0209: расширение каталога услуг (владелец, 2026-10-01).
--
-- По образцу каталога другого приложения: «сделать плюс-минус такие
-- категории; Разработку ПО и Дизайн не надо, остальное добавить».
-- Новые разделы: Грузоперевозки, Курьерские услуги, Компьютерная помощь,
-- Ремонт транспорта, Красота и здоровье, Репетиторы и обучение,
-- Мероприятия и промоакции, Фото, видео и аудио, Виртуальный помощник,
-- Юридическая и бухгалтерская помощь.
-- «Дом и быт» → «Уборка и помощь по хозяйству» (+ помощь по хозяйству,
-- няни и сиделки); «Грузчики и переезды» переезжают в «Грузоперевозки»,
-- раздел «Мастер на час и переезды» → «Мастер на час и разнорабочие».
-- Существующие категории и выбор специалистов не меняются.
-- Иконки — src/lib/category-icons.ts. После применения — npm run catalog:generate.
-- Сгенерировано скриптом из одного списка, вручную не править построчно.

BEGIN;

UPDATE public.categories_l1 SET name_ru = 'Уборка и помощь по хозяйству' WHERE id = 'home-services';
UPDATE public.categories_l1 SET name_ru = 'Мастер на час и разнорабочие' WHERE id = 'handyman-moving';

INSERT INTO public.categories_l1 (id, name_ru, icon, sort_order, is_active) VALUES
  ('cargo', 'Грузоперевозки', 'Truck', 8, true),
  ('courier', 'Курьерские услуги', 'Moped', 9, true),
  ('computer-help', 'Компьютерная помощь', 'Laptop', 10, true),
  ('auto', 'Ремонт транспорта', 'Car', 11, true),
  ('beauty', 'Красота и здоровье', 'Scissors', 12, true),
  ('tutors', 'Репетиторы и обучение', 'GraduationCap', 13, true),
  ('events', 'Мероприятия и промоакции', 'Confetti', 14, true),
  ('photo-video', 'Фото, видео и аудио', 'Camera', 15, true),
  ('virtual-assistant', 'Виртуальный помощник', 'Headset', 16, true),
  ('legal-accounting', 'Юридическая и бухгалтерская помощь', 'Scales', 17, true)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order, is_active = true;

UPDATE public.categories_l2 SET l1_id = 'cargo', sort_order = 20 WHERE id = 'movers';

INSERT INTO public.categories_l2 (id, l1_id, name_ru, icon, sort_order, is_active, is_visible, is_featured) VALUES
  ('cargo-transport', 'cargo', 'Грузоперевозки', 'Truck', 10, true, true, false),
  ('tow-truck', 'cargo', 'Эвакуатор', 'CarProfile', 30, true, true, false),
  ('courier-delivery', 'courier', 'Доставка документов и посылок', 'Package', 10, true, true, false),
  ('buy-deliver', 'courier', 'Купить и доставить', 'ShoppingBag', 20, true, true, false),
  ('food-delivery', 'courier', 'Доставка еды', 'ForkKnife', 30, true, true, false),
  ('pc-repair', 'computer-help', 'Ремонт компьютеров и ноутбуков', 'Laptop', 10, true, true, false),
  ('software-setup', 'computer-help', 'Настройка Windows и программ', 'Desktop', 20, true, true, false),
  ('internet-setup', 'computer-help', 'Интернет и Wi‑Fi', 'Broadcast', 30, true, true, false),
  ('phone-repair', 'computer-help', 'Ремонт телефонов и планшетов', 'DeviceMobile', 40, true, true, false),
  ('car-repair', 'auto', 'Автосервис и ремонт', 'Engine', 10, true, true, false),
  ('auto-electric', 'auto', 'Автоэлектрик', 'Lightning', 20, true, true, false),
  ('tire-service', 'auto', 'Шиномонтаж', 'Tire', 30, true, true, false),
  ('body-repair', 'auto', 'Кузовной ремонт и покраска', 'PaintBucket', 40, true, true, false),
  ('car-wash', 'auto', 'Автомойка и химчистка', 'Drop', 50, true, true, false),
  ('hairdresser', 'beauty', 'Парикмахеры', 'Scissors', 10, true, true, false),
  ('manicure', 'beauty', 'Маникюр и педикюр', 'Sparkle', 20, true, true, false),
  ('makeup', 'beauty', 'Визажисты', 'Sparkle', 30, true, true, false),
  ('massage', 'beauty', 'Массаж', 'HandHeart', 40, true, true, false),
  ('school-subjects', 'tutors', 'Школьные предметы', 'BookOpen', 10, true, true, false),
  ('exam-prep', 'tutors', 'Подготовка к ЕГЭ и ОГЭ', 'GraduationCap', 20, true, true, false),
  ('languages', 'tutors', 'Иностранные языки', 'Translate', 30, true, true, false),
  ('driving-instructor', 'tutors', 'Автоинструкторы', 'Car', 40, true, true, false),
  ('music-lessons', 'tutors', 'Уроки музыки', 'MusicNotes', 50, true, true, false),
  ('event-hosts', 'events', 'Ведущие и тамада', 'Microphone', 10, true, true, false),
  ('animators', 'events', 'Аниматоры', 'Balloon', 20, true, true, false),
  ('music-dj', 'events', 'Музыканты и диджеи', 'MusicNotes', 30, true, true, false),
  ('event-staff', 'events', 'Официанты и повара', 'ForkKnife', 40, true, true, false),
  ('event-decor', 'events', 'Оформление праздников', 'Cake', 50, true, true, false),
  ('promoters', 'events', 'Промоутеры', 'Megaphone', 60, true, true, false),
  ('photographer', 'photo-video', 'Фотографы', 'Camera', 10, true, true, false),
  ('videographer', 'photo-video', 'Видеосъёмка', 'VideoCamera', 20, true, true, false),
  ('video-editing', 'photo-video', 'Монтаж видео и звука', 'FilmSlate', 30, true, true, false),
  ('texts-docs', 'virtual-assistant', 'Тексты и документы', 'Keyboard', 10, true, true, false),
  ('info-search', 'virtual-assistant', 'Поиск информации', 'Compass', 20, true, true, false),
  ('calls-messages', 'virtual-assistant', 'Обзвон и переписка', 'Phone', 30, true, true, false),
  ('spreadsheets', 'virtual-assistant', 'Таблицы и базы', 'Rows', 40, true, true, false),
  ('lawyers', 'legal-accounting', 'Юристы', 'Gavel', 10, true, true, false),
  ('accountants', 'legal-accounting', 'Бухгалтеры', 'Calculator', 20, true, true, false),
  ('documents-help', 'legal-accounting', 'Помощь с документами', 'Briefcase', 30, true, true, false),
  ('housekeeping', 'home-services', 'Помощь по хозяйству', 'House', 70, true, true, false),
  ('caregivers', 'home-services', 'Няни и сиделки', 'Baby', 80, true, true, false)
ON CONFLICT (id) DO UPDATE SET l1_id = EXCLUDED.l1_id, name_ru = EXCLUDED.name_ru, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order, is_active = true, is_visible = true;

INSERT INTO public.categories_l3 (id, l2_id, name_ru, urgency_typical, sort_order) VALUES
  ('cargo-gazelle', 'cargo-transport', 'Газель с водителем', 'urgent', 10),
  ('cargo-furniture', 'cargo-transport', 'Перевезти мебель и технику', 'week', 20),
  ('cargo-materials', 'cargo-transport', 'Перевезти стройматериалы', 'week', 30),
  ('cargo-intercity', 'cargo-transport', 'Перевозка в другой город', 'week', 40),
  ('tow-car', 'tow-truck', 'Эвакуировать автомобиль', 'urgent', 10),
  ('tow-machinery', 'tow-truck', 'Перевезти спецтехнику', 'week', 20),
  ('courier-docs', 'courier-delivery', 'Доставить документы', 'urgent', 10),
  ('courier-parcel', 'courier-delivery', 'Доставить посылку', 'urgent', 20),
  ('courier-day', 'courier-delivery', 'Курьер на день', 'week', 30),
  ('buy-groceries', 'buy-deliver', 'Купить и привезти продукты', 'urgent', 10),
  ('buy-pharmacy', 'buy-deliver', 'Купить в аптеке', 'urgent', 20),
  ('buy-store', 'buy-deliver', 'Купить в магазине', 'urgent', 30),
  ('food-cafe', 'food-delivery', 'Доставка из кафе', 'urgent', 10),
  ('food-lunches', 'food-delivery', 'Доставка обедов', 'week', 20),
  ('pc-diagnostics', 'pc-repair', 'Диагностика', 'week', 10),
  ('pc-cleaning', 'pc-repair', 'Чистка от пыли', 'week', 20),
  ('pc-parts', 'pc-repair', 'Замена комплектующих', 'week', 30),
  ('pc-data', 'pc-repair', 'Восстановление данных', 'week', 40),
  ('sw-windows', 'software-setup', 'Установить Windows', 'week', 10),
  ('sw-virus', 'software-setup', 'Удалить вирусы', 'urgent', 20),
  ('sw-programs', 'software-setup', 'Установить программы', 'week', 30),
  ('net-router', 'internet-setup', 'Настроить роутер', 'urgent', 10),
  ('net-cable', 'internet-setup', 'Провести интернет-кабель', 'week', 20),
  ('phone-screen', 'phone-repair', 'Заменить экран', 'week', 10),
  ('phone-battery', 'phone-repair', 'Заменить аккумулятор', 'week', 20),
  ('phone-dead', 'phone-repair', 'Не включается', 'urgent', 30),
  ('car-diagnostics', 'car-repair', 'Диагностика автомобиля', 'week', 10),
  ('car-engine', 'car-repair', 'Ремонт двигателя', 'week', 20),
  ('car-suspension', 'car-repair', 'Ремонт ходовой', 'week', 30),
  ('car-oil', 'car-repair', 'Замена масла', 'week', 40),
  ('car-no-start', 'auto-electric', 'Машина не заводится', 'urgent', 10),
  ('car-alarm', 'auto-electric', 'Установить сигнализацию', 'week', 20),
  ('car-wiring', 'auto-electric', 'Ремонт проводки', 'week', 30),
  ('tire-season', 'tire-service', 'Сезонная замена шин', 'week', 10),
  ('tire-puncture', 'tire-service', 'Ремонт прокола', 'urgent', 20),
  ('tire-mobile', 'tire-service', 'Выездной шиномонтаж', 'urgent', 30),
  ('body-dents', 'body-repair', 'Убрать вмятины', 'week', 10),
  ('body-paint', 'body-repair', 'Покрасить автомобиль', 'month', 20),
  ('body-polish', 'body-repair', 'Полировка', 'week', 30),
  ('wash-interior', 'car-wash', 'Химчистка салона', 'week', 10),
  ('wash-mobile', 'car-wash', 'Выездная мойка', 'week', 20),
  ('hair-cut', 'hairdresser', 'Стрижка', 'week', 10),
  ('hair-color', 'hairdresser', 'Окрашивание', 'week', 20),
  ('hair-event', 'hairdresser', 'Причёска на торжество', 'week', 30),
  ('nails-manicure', 'manicure', 'Маникюр', 'week', 10),
  ('nails-pedicure', 'manicure', 'Педикюр', 'week', 20),
  ('nails-extension', 'manicure', 'Наращивание ногтей', 'week', 30),
  ('makeup-event', 'makeup', 'Макияж на торжество', 'week', 10),
  ('makeup-wedding', 'makeup', 'Свадебный макияж', 'month', 20),
  ('massage-classic', 'massage', 'Классический массаж', 'week', 10),
  ('massage-home', 'massage', 'Массаж на дому', 'week', 20),
  ('tutor-math', 'school-subjects', 'Математика', 'week', 10),
  ('tutor-russian', 'school-subjects', 'Русский язык', 'week', 20),
  ('tutor-science', 'school-subjects', 'Физика и химия', 'week', 30),
  ('tutor-primary', 'school-subjects', 'Начальная школа', 'week', 40),
  ('exam-ege', 'exam-prep', 'Подготовка к ЕГЭ', 'month', 10),
  ('exam-oge', 'exam-prep', 'Подготовка к ОГЭ', 'month', 20),
  ('lang-english', 'languages', 'Английский', 'week', 10),
  ('lang-arabic', 'languages', 'Арабский', 'week', 20),
  ('lang-other', 'languages', 'Другие языки', 'week', 30),
  ('drive-beginner', 'driving-instructor', 'Вождение для начинающих', 'week', 10),
  ('drive-refresh', 'driving-instructor', 'Восстановить навыки вождения', 'week', 20),
  ('music-guitar', 'music-lessons', 'Гитара', 'week', 10),
  ('music-piano', 'music-lessons', 'Фортепиано', 'week', 20),
  ('music-vocal', 'music-lessons', 'Вокал', 'week', 30),
  ('host-wedding', 'event-hosts', 'Ведущий на свадьбу', 'month', 10),
  ('host-party', 'event-hosts', 'Ведущий на праздник', 'week', 20),
  ('anim-kids', 'animators', 'Детский праздник', 'week', 10),
  ('anim-birthday', 'animators', 'Аниматор на день рождения', 'week', 20),
  ('dj', 'music-dj', 'Диджей', 'week', 10),
  ('musicians-wedding', 'music-dj', 'Музыканты на свадьбу', 'month', 20),
  ('staff-waiters', 'event-staff', 'Официанты на мероприятие', 'week', 10),
  ('staff-cook', 'event-staff', 'Повар на мероприятие', 'week', 20),
  ('decor-balloons', 'event-decor', 'Оформление шарами', 'week', 10),
  ('decor-hall', 'event-decor', 'Оформление зала', 'week', 20),
  ('promo-flyers', 'promoters', 'Раздать листовки', 'week', 10),
  ('promo-instore', 'promoters', 'Промоакция в магазине', 'week', 20),
  ('photo-event', 'photographer', 'Фотосъёмка мероприятия', 'week', 10),
  ('photo-wedding', 'photographer', 'Свадебная съёмка', 'month', 20),
  ('photo-session', 'photographer', 'Фотосессия', 'week', 30),
  ('photo-product', 'photographer', 'Предметная съёмка', 'week', 40),
  ('video-event', 'videographer', 'Видеосъёмка мероприятия', 'week', 10),
  ('video-wedding', 'videographer', 'Свадебное видео', 'month', 20),
  ('video-drone', 'videographer', 'Съёмка с дрона', 'week', 30),
  ('edit-video', 'video-editing', 'Смонтировать видео', 'week', 10),
  ('edit-audio', 'video-editing', 'Обработать звук', 'week', 20),
  ('va-typing', 'texts-docs', 'Набрать текст', 'week', 10),
  ('va-docs', 'texts-docs', 'Оформить документ', 'week', 20),
  ('va-translate', 'texts-docs', 'Перевести текст', 'week', 30),
  ('va-research', 'info-search', 'Найти информацию', 'week', 10),
  ('va-compare', 'info-search', 'Сравнить цены', 'week', 20),
  ('va-calls', 'calls-messages', 'Обзвонить клиентов', 'week', 10),
  ('va-replies', 'calls-messages', 'Отвечать на сообщения', 'week', 20),
  ('va-tables', 'spreadsheets', 'Заполнить таблицы', 'week', 10),
  ('va-database', 'spreadsheets', 'Вести базу', 'week', 20),
  ('law-consult', 'lawyers', 'Консультация юриста', 'week', 10),
  ('law-contract', 'lawyers', 'Составить договор', 'week', 20),
  ('law-court', 'lawyers', 'Представительство в суде', 'month', 30),
  ('acc-declaration', 'accountants', 'Налоговая декларация', 'week', 10),
  ('acc-ip', 'accountants', 'Бухгалтерия для ИП', 'month', 20),
  ('acc-reports', 'accountants', 'Сдать отчётность', 'week', 30),
  ('docs-mfc', 'documents-help', 'Оформить документы', 'week', 10),
  ('docs-company', 'documents-help', 'Зарегистрировать ИП или ООО', 'week', 20),
  ('house-help', 'housekeeping', 'Домработница', 'week', 10),
  ('house-cooking', 'housekeeping', 'Помощь с готовкой', 'week', 20),
  ('house-ironing', 'housekeeping', 'Глажка белья', 'week', 30),
  ('care-nanny', 'caregivers', 'Няня', 'week', 10),
  ('care-elderly', 'caregivers', 'Сиделка для пожилых', 'week', 20)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.category_terms (l2_id, term, weight)
SELECT v.l2_id, v.term, v.weight
  FROM (VALUES
    ('cargo-transport', 'грузоперевозки', 100),
    ('cargo-transport', 'газель', 90),
    ('cargo-transport', 'грузовое такси', 80),
    ('cargo-transport', 'перевезти', 70),
    ('cargo-transport', 'перевозка', 60),
    ('tow-truck', 'эвакуатор', 100),
    ('tow-truck', 'эвакуация', 90),
    ('courier-delivery', 'курьер', 100),
    ('courier-delivery', 'доставка', 90),
    ('courier-delivery', 'доставить', 80),
    ('courier-delivery', 'посылка', 70),
    ('buy-deliver', 'купить и доставить', 100),
    ('buy-deliver', 'привезти продукты', 90),
    ('buy-deliver', 'купить', 80),
    ('food-delivery', 'доставка еды', 100),
    ('food-delivery', 'еда', 90),
    ('food-delivery', 'обеды', 80),
    ('pc-repair', 'компьютер', 100),
    ('pc-repair', 'ноутбук', 90),
    ('pc-repair', 'ремонт компьютера', 80),
    ('pc-repair', 'ремонт ноутбука', 70),
    ('software-setup', 'windows', 100),
    ('software-setup', 'программы', 90),
    ('software-setup', 'вирусы', 80),
    ('software-setup', 'настройка компьютера', 70),
    ('internet-setup', 'интернет', 100),
    ('internet-setup', 'wi-fi', 90),
    ('internet-setup', 'вайфай', 80),
    ('internet-setup', 'роутер', 70),
    ('phone-repair', 'телефон', 100),
    ('phone-repair', 'смартфон', 90),
    ('phone-repair', 'айфон', 80),
    ('phone-repair', 'планшет', 70),
    ('phone-repair', 'ремонт телефона', 60),
    ('car-repair', 'автосервис', 100),
    ('car-repair', 'ремонт машины', 90),
    ('car-repair', 'автомеханик', 80),
    ('car-repair', 'авто', 70),
    ('auto-electric', 'автоэлектрик', 100),
    ('auto-electric', 'сигнализация', 90),
    ('tire-service', 'шиномонтаж', 100),
    ('tire-service', 'шины', 90),
    ('tire-service', 'колесо', 80),
    ('body-repair', 'кузовной ремонт', 100),
    ('body-repair', 'покраска авто', 90),
    ('body-repair', 'вмятина', 80),
    ('car-wash', 'автомойка', 100),
    ('car-wash', 'химчистка салона', 90),
    ('car-wash', 'мойка', 80),
    ('hairdresser', 'парикмахер', 100),
    ('hairdresser', 'стрижка', 90),
    ('hairdresser', 'причёска', 80),
    ('manicure', 'маникюр', 100),
    ('manicure', 'педикюр', 90),
    ('manicure', 'ногти', 80),
    ('makeup', 'визажист', 100),
    ('makeup', 'макияж', 90),
    ('massage', 'массаж', 100),
    ('massage', 'массажист', 90),
    ('school-subjects', 'репетитор', 100),
    ('school-subjects', 'математика', 90),
    ('school-subjects', 'русский язык', 80),
    ('school-subjects', 'школа', 70),
    ('exam-prep', 'егэ', 100),
    ('exam-prep', 'огэ', 90),
    ('exam-prep', 'подготовка к экзамену', 80),
    ('languages', 'английский', 100),
    ('languages', 'арабский', 90),
    ('languages', 'иностранный язык', 80),
    ('driving-instructor', 'автоинструктор', 100),
    ('driving-instructor', 'вождение', 90),
    ('driving-instructor', 'инструктор', 80),
    ('music-lessons', 'уроки музыки', 100),
    ('music-lessons', 'гитара', 90),
    ('music-lessons', 'фортепиано', 80),
    ('music-lessons', 'вокал', 70),
    ('event-hosts', 'ведущий', 100),
    ('event-hosts', 'тамада', 90),
    ('event-hosts', 'свадьба', 80),
    ('animators', 'аниматор', 100),
    ('animators', 'детский праздник', 90),
    ('animators', 'день рождения', 80),
    ('music-dj', 'диджей', 100),
    ('music-dj', 'музыканты', 90),
    ('music-dj', 'живая музыка', 80),
    ('event-staff', 'официант', 100),
    ('event-staff', 'повар', 90),
    ('event-staff', 'кейтеринг', 80),
    ('event-decor', 'оформление праздника', 100),
    ('event-decor', 'шары', 90),
    ('event-decor', 'декор', 80),
    ('promoters', 'промоутер', 100),
    ('promoters', 'листовки', 90),
    ('promoters', 'промоакция', 80),
    ('photographer', 'фотограф', 100),
    ('photographer', 'фотосъёмка', 90),
    ('photographer', 'фотосессия', 80),
    ('videographer', 'видеограф', 100),
    ('videographer', 'видеосъёмка', 90),
    ('videographer', 'видео', 80),
    ('video-editing', 'монтаж видео', 100),
    ('video-editing', 'монтаж', 90),
    ('video-editing', 'звук', 80),
    ('texts-docs', 'набор текста', 100),
    ('texts-docs', 'документы', 90),
    ('texts-docs', 'перевод', 80),
    ('info-search', 'поиск информации', 100),
    ('info-search', 'найти', 90),
    ('calls-messages', 'обзвон', 100),
    ('calls-messages', 'звонки', 90),
    ('calls-messages', 'переписка', 80),
    ('spreadsheets', 'таблицы', 100),
    ('spreadsheets', 'excel', 90),
    ('spreadsheets', 'база данных', 80),
    ('lawyers', 'юрист', 100),
    ('lawyers', 'адвокат', 90),
    ('lawyers', 'договор', 80),
    ('lawyers', 'консультация', 70),
    ('accountants', 'бухгалтер', 100),
    ('accountants', 'декларация', 90),
    ('accountants', 'отчётность', 80),
    ('accountants', 'налоги', 70),
    ('documents-help', 'оформление документов', 100),
    ('documents-help', 'регистрация ип', 90),
    ('documents-help', 'мфц', 80),
    ('housekeeping', 'домработница', 100),
    ('housekeeping', 'помощь по хозяйству', 90),
    ('housekeeping', 'готовка', 80),
    ('housekeeping', 'глажка', 70),
    ('caregivers', 'няня', 100),
    ('caregivers', 'сиделка', 90),
    ('caregivers', 'уход', 80)
  ) AS v(l2_id, term, weight)
 WHERE NOT EXISTS (
   SELECT 1 FROM public.category_terms t
    WHERE t.l2_id = v.l2_id AND lower(t.term) = lower(v.term));

NOTIFY pgrst, 'reload schema';

COMMIT;
