/** Словарь формулировок задач (№248) — подсказки первого экрана создания задания, как у YouDo. Каждая формулировка ведёт в свою подкатегорию. */
export interface TaskPhrase {
  /** Как человек назвал бы задачу: «Отремонтировать газовый котёл». */
  text: string;
  /** id подкатегории (categories_l2.id) из src/generated/task-catalog.json. */
  l2: string;
  /** Насколько частая задача, 1–100: порядок подсказок при равном совпадении. */
  weight: number;
}

// Правила словаря: формулировка — глагол в инфинитиве + объект или короткая
// услуга; без брендов; до 60 символов; без дублей (регистр и ё/е не важны).
// weight: 80–100 — массовые бытовые задачи, 40–70 — частые, 10–30 — редкие.
// «спорно: …» — задача, которую может выполнить и специалист другой категории;
// выбрана категория, куда реально пойдёт исполнитель.
export const TASK_PHRASES: readonly TaskPhrase[] = [
  // ── renovation — Ремонт и отделка ──
  { text: "Сделать ремонт квартиры", l2: "renovation", weight: 95 },
  { text: "Косметический ремонт квартиры", l2: "renovation", weight: 85 },
  { text: "Капитальный ремонт квартиры", l2: "renovation", weight: 70 },
  { text: "Ремонт квартиры под ключ", l2: "renovation", weight: 75 },
  { text: "Отремонтировать ванную комнату", l2: "renovation", weight: 80 },
  { text: "Ремонт ванной под ключ", l2: "renovation", weight: 60 },
  { text: "Ремонт санузла", l2: "renovation", weight: 65 },
  { text: "Ремонт туалета под ключ", l2: "renovation", weight: 45 },
  { text: "Отремонтировать кухню", l2: "renovation", weight: 70 },
  { text: "Ремонт кухни под ключ", l2: "renovation", weight: 50 },
  { text: "Сделать ремонт в частном доме", l2: "renovation", weight: 75 },
  { text: "Внутренняя отделка дома", l2: "renovation", weight: 55 },
  { text: "Черновая отделка дома", l2: "renovation", weight: 40 },
  { text: "Чистовая отделка квартиры", l2: "renovation", weight: 45 },
  { text: "Ремонт в новостройке", l2: "renovation", weight: 50 },
  { text: "Ремонт комнаты", l2: "renovation", weight: 60 },
  { text: "Ремонт коридора", l2: "renovation", weight: 35 },
  { text: "Ремонт детской комнаты", l2: "renovation", weight: 30 },
  { text: "Отремонтировать балкон", l2: "renovation", weight: 45 },
  { text: "Отделка лоджии", l2: "renovation", weight: 30 },
  { text: "Ремонт офиса", l2: "renovation", weight: 30 },
  { text: "Ремонт магазина", l2: "renovation", weight: 20 },
  // ── windows — Окна и остекление ──
  { text: "Установить пластиковые окна", l2: "windows", weight: 70 },
  { text: "Заменить окна", l2: "windows", weight: 65 },
  { text: "Отремонтировать пластиковое окно", l2: "windows", weight: 50 },
  { text: "Отрегулировать окна", l2: "windows", weight: 45 },
  { text: "Заменить стеклопакет", l2: "windows", weight: 40 },
  { text: "Застеклить балкон", l2: "windows", weight: 50 },
  { text: "Остекление лоджии", l2: "windows", weight: 35 },
  { text: "Установить откосы на окна", l2: "windows", weight: 35 },
  { text: "Установить москитную сетку", l2: "windows", weight: 40 },
  { text: "Заменить уплотнитель на окнах", l2: "windows", weight: 25 },
  { text: "Установить подоконник", l2: "windows", weight: 30 },
  { text: "Установить алюминиевые окна", l2: "windows", weight: 20 },
  { text: "Заменить фурнитуру на окне", l2: "windows", weight: 20 },
  // спорно: может прийти и кровельщик (roofing)
  { text: "Установить мансардное окно", l2: "windows", weight: 15 },
  // ── doors — Двери ──
  { text: "Установить входную дверь", l2: "doors", weight: 65 },
  { text: "Установить металлическую дверь", l2: "doors", weight: 40 },
  { text: "Поменять входную дверь", l2: "doors", weight: 50 },
  { text: "Установить межкомнатную дверь", l2: "doors", weight: 60 },
  { text: "Установить двери в доме", l2: "doors", weight: 35 },
  { text: "Отремонтировать дверь", l2: "doors", weight: 45 },
  { text: "Установить раздвижную дверь", l2: "doors", weight: 25 },
  { text: "Установить доводчик на дверь", l2: "doors", weight: 30 },
  { text: "Заменить дверную коробку", l2: "doors", weight: 20 },
  { text: "Подрезать межкомнатную дверь", l2: "doors", weight: 20 },
  { text: "Отреставрировать старую дверь", l2: "doors", weight: 15 },
  { text: "Утеплить входную дверь", l2: "doors", weight: 20 },
  { text: "Обшить входную дверь панелями", l2: "doors", weight: 15 },
  // ── painting — Штукатурка и покраска ──
  { text: "Покрасить стены", l2: "painting", weight: 70 },
  { text: "Покрасить потолок", l2: "painting", weight: 55 },
  { text: "Побелить потолок", l2: "painting", weight: 40 },
  { text: "Покрасить радиаторы", l2: "painting", weight: 25 },
  { text: "Покрасить трубы", l2: "painting", weight: 20 },
  { text: "Отштукатурить стены", l2: "painting", weight: 60 },
  { text: "Выровнять стены", l2: "painting", weight: 60 },
  { text: "Зашпаклевать стены", l2: "painting", weight: 55 },
  { text: "Шпаклёвка потолка", l2: "painting", weight: 35 },
  { text: "Штукатурка стен по маякам", l2: "painting", weight: 40 },
  { text: "Машинная штукатурка стен", l2: "painting", weight: 35 },
  { text: "Декоративная штукатурка", l2: "painting", weight: 35 },
  { text: "Венецианская штукатурка", l2: "painting", weight: 20 },
  { text: "Шлифовка стен", l2: "painting", weight: 20 },
  { text: "Нанести микроцемент", l2: "painting", weight: 15 },
  // ── wallpaper — Обои ──
  { text: "Поклеить обои", l2: "wallpaper", weight: 95 },
  { text: "Переклеить обои", l2: "wallpaper", weight: 70 },
  { text: "Поклеить обои в комнате", l2: "wallpaper", weight: 60 },
  { text: "Поклеить обои в коридоре", l2: "wallpaper", weight: 30 },
  { text: "Поклеить обои на потолок", l2: "wallpaper", weight: 20 },
  { text: "Поклеить флизелиновые обои", l2: "wallpaper", weight: 45 },
  { text: "Поклеить виниловые обои", l2: "wallpaper", weight: 40 },
  { text: "Поклеить бумажные обои", l2: "wallpaper", weight: 20 },
  { text: "Поклеить обои под покраску", l2: "wallpaper", weight: 35 },
  { text: "Поклеить фотообои", l2: "wallpaper", weight: 35 },
  { text: "Поклеить стеклообои", l2: "wallpaper", weight: 15 },
  { text: "Нанести жидкие обои", l2: "wallpaper", weight: 30 },
  { text: "Снять старые обои", l2: "wallpaper", weight: 40 },
  { text: "Подклеить отошедшие обои", l2: "wallpaper", weight: 30 },
  { text: "Обойщик", l2: "wallpaper", weight: 30 },
  // ── drywall — Гипсокартон ──
  { text: "Сделать перегородку из гипсокартона", l2: "drywall", weight: 55 },
  // спорно: в каталоге есть и ceilings «Гипсокартонный потолок»; делает гипсокартонщик
  { text: "Сделать потолок из гипсокартона", l2: "drywall", weight: 45 },
  { text: "Многоуровневый потолок из гипсокартона", l2: "drywall", weight: 25 },
  { text: "Обшить стены гипсокартоном", l2: "drywall", weight: 45 },
  { text: "Зашить трубы гипсокартоном", l2: "drywall", weight: 45 },
  { text: "Сделать короб из гипсокартона", l2: "drywall", weight: 35 },
  { text: "Сделать арку из гипсокартона", l2: "drywall", weight: 30 },
  { text: "Сделать нишу из гипсокартона", l2: "drywall", weight: 25 },
  { text: "Сделать полки из гипсокартона", l2: "drywall", weight: 15 },
  { text: "Монтаж гипсокартона", l2: "drywall", weight: 40 },
  { text: "Мастер по гипсокартону", l2: "drywall", weight: 30 },
  // ── tiling — Плитка и мозаика ──
  { text: "Укладка плитки", l2: "tiling", weight: 70 },
  { text: "Положить плитку в ванной", l2: "tiling", weight: 80 },
  { text: "Положить плитку в туалете", l2: "tiling", weight: 45 },
  { text: "Положить плитку на пол", l2: "tiling", weight: 65 },
  { text: "Положить плитку на крыльцо", l2: "tiling", weight: 35 },
  { text: "Облицевать санузел плиткой", l2: "tiling", weight: 50 },
  { text: "Переложить плитку в ванной", l2: "tiling", weight: 35 },
  { text: "Сделать кухонный фартук из плитки", l2: "tiling", weight: 45 },
  { text: "Положить керамогранит", l2: "tiling", weight: 40 },
  { text: "Уложить крупноформатную плитку", l2: "tiling", weight: 15 },
  { text: "Уложить мозаику", l2: "tiling", weight: 20 },
  { text: "Затереть швы плитки", l2: "tiling", weight: 30 },
  { text: "Заменить затирку в ванной", l2: "tiling", weight: 25 },
  { text: "Заменить отвалившуюся плитку", l2: "tiling", weight: 30 },
  { text: "Облицевать лестницу плиткой", l2: "tiling", weight: 20 },
  { text: "Плиточник", l2: "tiling", weight: 50 },
  // ── floors — Полы и стяжка ──
  { text: "Постелить ламинат", l2: "floors", weight: 70 },
  { text: "Уложить ламинат", l2: "floors", weight: 60 },
  { text: "Постелить линолеум", l2: "floors", weight: 55 },
  { text: "Уложить паркетную доску", l2: "floors", weight: 30 },
  { text: "Положить кварц-винил", l2: "floors", weight: 25 },
  { text: "Положить ковролин", l2: "floors", weight: 15 },
  { text: "Залить стяжку пола", l2: "floors", weight: 55 },
  { text: "Сухая стяжка пола", l2: "floors", weight: 20 },
  { text: "Сделать наливной пол", l2: "floors", weight: 40 },
  { text: "Выровнять пол", l2: "floors", weight: 45 },
  { text: "Заменить полы", l2: "floors", weight: 40 },
  // спорно: термин «тёплый пол» в каталоге есть и у climate, но услуги — в floors
  { text: "Сделать тёплый пол", l2: "floors", weight: 50 },
  { text: "Уложить электрический тёплый пол", l2: "floors", weight: 35 },
  { text: "Водяной тёплый пол", l2: "floors", weight: 30 },
  { text: "Отциклевать паркет", l2: "floors", weight: 25 },
  { text: "Установить плинтус", l2: "floors", weight: 35 },
  { text: "Отремонтировать скрипучий пол", l2: "floors", weight: 20 },
  // ── plumbing — Сантехника ──
  { text: "Услуги сантехника", l2: "plumbing", weight: 90 },
  { text: "Сантехник на час", l2: "plumbing", weight: 50 },
  { text: "Заменить смеситель", l2: "plumbing", weight: 85 },
  { text: "Поменять смеситель", l2: "plumbing", weight: 70 },
  { text: "Починить кран", l2: "plumbing", weight: 75 },
  { text: "Устранить протечку", l2: "plumbing", weight: 65 },
  { text: "Заменить шаровой кран", l2: "plumbing", weight: 30 },
  { text: "Установить унитаз", l2: "plumbing", weight: 75 },
  { text: "Заменить унитаз", l2: "plumbing", weight: 60 },
  { text: "Починить унитаз", l2: "plumbing", weight: 65 },
  { text: "Отремонтировать бачок унитаза", l2: "plumbing", weight: 55 },
  { text: "Установить инсталляцию", l2: "plumbing", weight: 35 },
  { text: "Установить ванну", l2: "plumbing", weight: 50 },
  { text: "Установить душевую кабину", l2: "plumbing", weight: 55 },
  { text: "Установить раковину", l2: "plumbing", weight: 55 },
  { text: "Установить мойку на кухне", l2: "plumbing", weight: 50 },
  { text: "Заменить сифон", l2: "plumbing", weight: 35 },
  { text: "Прочистить засор", l2: "plumbing", weight: 80 },
  { text: "Прочистить канализацию", l2: "plumbing", weight: 65 },
  { text: "Прочистить раковину", l2: "plumbing", weight: 45 },
  { text: "Установить счётчики воды", l2: "plumbing", weight: 50 },
  { text: "Заменить счётчик воды", l2: "plumbing", weight: 40 },
  { text: "Поверка счётчиков воды", l2: "plumbing", weight: 40 },
  { text: "Установить водонагреватель", l2: "plumbing", weight: 60 },
  { text: "Установить бойлер", l2: "plumbing", weight: 45 },
  // спорно: может и ремонт техники; в каталоге водонагреватель — у plumbing
  { text: "Отремонтировать водонагреватель", l2: "plumbing", weight: 40 },
  { text: "Подключить стиральную машину", l2: "plumbing", weight: 65 },
  { text: "Подключить посудомоечную машину", l2: "plumbing", weight: 50 },
  { text: "Установить фильтр для воды", l2: "plumbing", weight: 40 },
  // спорно: подключается к отоплению или ГВС; обычно ставит сантехник
  { text: "Установить полотенцесушитель", l2: "plumbing", weight: 40 },
  // ── water-sewer — Водоснабжение и канализация ──
  { text: "Провести воду в дом", l2: "water-sewer", weight: 50 },
  { text: "Развести воду по дому", l2: "water-sewer", weight: 45 },
  { text: "Заменить трубы водопровода", l2: "water-sewer", weight: 50 },
  { text: "Подключить дом к водопроводу", l2: "water-sewer", weight: 30 },
  { text: "Утеплить трубы водопровода", l2: "water-sewer", weight: 25 },
  { text: "Сделать канализацию в доме", l2: "water-sewer", weight: 45 },
  { text: "Провести наружную канализацию", l2: "water-sewer", weight: 35 },
  { text: "Заменить канализационные трубы", l2: "water-sewer", weight: 40 },
  { text: "Установить септик", l2: "water-sewer", weight: 50 },
  { text: "Сделать выгребную яму", l2: "water-sewer", weight: 30 },
  { text: "Откачать септик", l2: "water-sewer", weight: 55 },
  { text: "Вызвать ассенизатор", l2: "water-sewer", weight: 50 },
  { text: "Установить насосную станцию", l2: "water-sewer", weight: 40 },
  { text: "Отремонтировать насосную станцию", l2: "water-sewer", weight: 30 },
  { text: "Устранить прорыв трубы", l2: "water-sewer", weight: 50 },
  { text: "Аварийный сантехник", l2: "water-sewer", weight: 55 },
  // ── electrical — Электрика ──
  { text: "Услуги электрика", l2: "electrical", weight: 95 },
  { text: "Электрик на час", l2: "electrical", weight: 50 },
  { text: "Заменить розетку", l2: "electrical", weight: 75 },
  { text: "Поменять розетку", l2: "electrical", weight: 55 },
  { text: "Установить розетку", l2: "electrical", weight: 60 },
  { text: "Перенести розетку", l2: "electrical", weight: 40 },
  { text: "Заменить выключатель", l2: "electrical", weight: 55 },
  { text: "Повесить люстру", l2: "electrical", weight: 70 },
  { text: "Установить люстру", l2: "electrical", weight: 50 },
  { text: "Установить светильники", l2: "electrical", weight: 45 },
  { text: "Установить точечные светильники", l2: "electrical", weight: 40 },
  { text: "Установить LED-подсветку", l2: "electrical", weight: 30 },
  { text: "Заменить проводку в квартире", l2: "electrical", weight: 55 },
  { text: "Сделать электропроводку в доме", l2: "electrical", weight: 60 },
  { text: "Провести свет в гараж", l2: "electrical", weight: 30 },
  { text: "Найти неисправность в проводке", l2: "electrical", weight: 50 },
  { text: "Восстановить свет в доме", l2: "electrical", weight: 45 },
  { text: "Устранить короткое замыкание", l2: "electrical", weight: 45 },
  { text: "Собрать электрощит", l2: "electrical", weight: 40 },
  { text: "Установить электросчётчик", l2: "electrical", weight: 45 },
  { text: "Заменить электросчётчик", l2: "electrical", weight: 35 },
  { text: "Установить автоматы и УЗО", l2: "electrical", weight: 35 },
  { text: "Сделать заземление", l2: "electrical", weight: 35 },
  { text: "Подключить дом к электросети", l2: "electrical", weight: 35 },
  { text: "Установить стабилизатор напряжения", l2: "electrical", weight: 30 },
  { text: "Установить датчик движения", l2: "electrical", weight: 20 },
  // спорно: в appliance-repair есть «Установка бытовой техники»; подключение к сети — электрик
  { text: "Подключить электроплиту", l2: "electrical", weight: 45 },
  // спорно: то же, что электроплита
  { text: "Подключить варочную панель", l2: "electrical", weight: 35 },
  // ── climate — Отопление и котлы ──
  { text: "Отремонтировать газовый котёл", l2: "climate", weight: 90 },
  { text: "Починить газовый котёл", l2: "climate", weight: 75 },
  { text: "Установить газовый котёл", l2: "climate", weight: 75 },
  { text: "Заменить газовый котёл", l2: "climate", weight: 55 },
  { text: "Настроить газовый котёл", l2: "climate", weight: 40 },
  { text: "Обслуживание газового котла", l2: "climate", weight: 60 },
  { text: "Почистить газовый котёл", l2: "climate", weight: 55 },
  // спорно: врезку в газовую сеть делает газовая служба, не частный мастер
  { text: "Подключить котёл к газу", l2: "climate", weight: 40 },
  { text: "Отремонтировать котёл", l2: "climate", weight: 70 },
  { text: "Отремонтировать электрический котёл", l2: "climate", weight: 45 },
  { text: "Установить электрический котёл", l2: "climate", weight: 45 },
  { text: "Отремонтировать твердотопливный котёл", l2: "climate", weight: 25 },
  { text: "Установить твердотопливный котёл", l2: "climate", weight: 20 },
  { text: "Отремонтировать дизельный котёл", l2: "climate", weight: 10 },
  // спорно: колонка греет воду (plumbing), но чинит тот же газовщик, что и котёл
  { text: "Отремонтировать газовую колонку", l2: "climate", weight: 55 },
  // спорно: как ремонт колонки
  { text: "Установить газовую колонку", l2: "climate", weight: 45 },
  { text: "Почистить газовую колонку", l2: "climate", weight: 35 },
  { text: "Сделать отопление в доме", l2: "climate", weight: 65 },
  { text: "Монтаж отопления в частном доме", l2: "climate", weight: 50 },
  { text: "Установить радиаторы отопления", l2: "climate", weight: 60 },
  { text: "Заменить батареи отопления", l2: "climate", weight: 60 },
  { text: "Перенести батарею", l2: "climate", weight: 35 },
  { text: "Спустить воздух из батарей", l2: "climate", weight: 30 },
  { text: "Промыть систему отопления", l2: "climate", weight: 40 },
  { text: "Опрессовка системы отопления", l2: "climate", weight: 25 },
  { text: "Установить дымоход для котла", l2: "climate", weight: 35 },
  { text: "Установить циркуляционный насос", l2: "climate", weight: 30 },
  { text: "Установить расширительный бак", l2: "climate", weight: 20 },
  { text: "Установить тёплый плинтус", l2: "climate", weight: 15 },
  // ── climate-control — Кондиционеры и вентиляция ──
  { text: "Установить кондиционер", l2: "climate-control", weight: 90 },
  { text: "Установка сплит-системы", l2: "climate-control", weight: 50 },
  { text: "Отремонтировать кондиционер", l2: "climate-control", weight: 75 },
  { text: "Починить кондиционер", l2: "climate-control", weight: 60 },
  { text: "Отремонтировать сплит-систему", l2: "climate-control", weight: 35 },
  { text: "Почистить кондиционер", l2: "climate-control", weight: 65 },
  { text: "Заправить кондиционер", l2: "climate-control", weight: 65 },
  { text: "Обслуживание кондиционера", l2: "climate-control", weight: 50 },
  { text: "Демонтировать кондиционер", l2: "climate-control", weight: 40 },
  { text: "Перенести кондиционер", l2: "climate-control", weight: 35 },
  { text: "Установить мульти-сплит-систему", l2: "climate-control", weight: 15 },
  { text: "Установить вентиляцию", l2: "climate-control", weight: 40 },
  { text: "Сделать вентиляцию в доме", l2: "climate-control", weight: 35 },
  { text: "Приточно-вытяжная вентиляция", l2: "climate-control", weight: 25 },
  { text: "Почистить вентиляцию", l2: "climate-control", weight: 25 },
  // спорно: часто ставит электрик или мастер на час
  { text: "Установить вытяжку в ванной", l2: "climate-control", weight: 35 },
  // ── insulation — Утепление и изоляция ──
  { text: "Утеплить стены изнутри", l2: "insulation", weight: 40 },
  { text: "Утеплить пол", l2: "insulation", weight: 35 },
  { text: "Утеплить потолок в доме", l2: "insulation", weight: 30 },
  { text: "Утеплить балкон", l2: "insulation", weight: 40 },
  { text: "Утеплить гараж", l2: "insulation", weight: 15 },
  // спорно: может и кровельщик (roofing «Утепление кровли»)
  { text: "Утеплить мансарду", l2: "insulation", weight: 25 },
  { text: "Сделать шумоизоляцию стен", l2: "insulation", weight: 35 },
  { text: "Шумоизоляция потолка", l2: "insulation", weight: 20 },
  { text: "Сделать гидроизоляцию подвала", l2: "insulation", weight: 30 },
  { text: "Сделать пароизоляцию", l2: "insulation", weight: 15 },
  // ── roofing — Кровля ──
  { text: "Перекрыть крышу", l2: "roofing", weight: 60 },
  { text: "Отремонтировать крышу", l2: "roofing", weight: 65 },
  { text: "Устранить протечку крыши", l2: "roofing", weight: 55 },
  { text: "Сделать кровлю под ключ", l2: "roofing", weight: 40 },
  { text: "Покрыть крышу металлочерепицей", l2: "roofing", weight: 50 },
  { text: "Покрыть крышу профнастилом", l2: "roofing", weight: 45 },
  { text: "Покрыть крышу ондулином", l2: "roofing", weight: 20 },
  { text: "Сделать мягкую кровлю", l2: "roofing", weight: 30 },
  { text: "Утеплить крышу", l2: "roofing", weight: 35 },
  { text: "Установить водостоки", l2: "roofing", weight: 45 },
  { text: "Установить снегозадержатели", l2: "roofing", weight: 25 },
  { text: "Отремонтировать кровлю гаража", l2: "roofing", weight: 20 },
  // ── facade — Фасадные работы ──
  { text: "Оштукатурить фасад дома", l2: "facade", weight: 45 },
  { text: "Сделать короед на фасаде", l2: "facade", weight: 30 },
  { text: "Покрасить фасад", l2: "facade", weight: 40 },
  { text: "Обшить дом сайдингом", l2: "facade", weight: 50 },
  { text: "Облицевать дом камнем", l2: "facade", weight: 35 },
  { text: "Облицевать дом кирпичом", l2: "facade", weight: 30 },
  { text: "Отделать фасад травертином", l2: "facade", weight: 20 },
  { text: "Облицевать цоколь", l2: "facade", weight: 30 },
  { text: "Утеплить фасад", l2: "facade", weight: 45 },
  { text: "Сделать вентилируемый фасад", l2: "facade", weight: 20 },
  // ── concrete — Бетонные работы ──
  { text: "Залить фундамент", l2: "concrete", weight: 70 },
  { text: "Залить ленточный фундамент", l2: "concrete", weight: 40 },
  { text: "Сделать армопояс", l2: "concrete", weight: 30 },
  { text: "Сделать монолитное перекрытие", l2: "concrete", weight: 30 },
  { text: "Залить бетонную лестницу", l2: "concrete", weight: 25 },
  { text: "Залить черновой пол бетоном", l2: "concrete", weight: 30 },
  { text: "Залить отмостку вокруг дома", l2: "concrete", weight: 40 },
  // спорно: могут искать как благоустройство (landscape)
  { text: "Забетонировать двор", l2: "concrete", weight: 45 },
  { text: "Залить площадку под машину", l2: "concrete", weight: 30 },
  { text: "Сделать опалубку", l2: "concrete", weight: 20 },
  { text: "Алмазное бурение отверстий", l2: "concrete", weight: 25 },
  { text: "Резка бетона", l2: "concrete", weight: 20 },
  { text: "Бригада бетонщиков", l2: "concrete", weight: 30 },
  // ── masonry — Каменщики и кладка ──
  { text: "Кладка кирпича", l2: "masonry", weight: 50 },
  { text: "Кладка газоблоков", l2: "masonry", weight: 45 },
  { text: "Кладка пеноблоков", l2: "masonry", weight: 30 },
  { text: "Кладка ракушечника", l2: "masonry", weight: 15 },
  { text: "Кладка облицовочного кирпича", l2: "masonry", weight: 30 },
  { text: "Сделать кирпичную перегородку", l2: "masonry", weight: 30 },
  { text: "Выложить колонны из кирпича", l2: "masonry", weight: 20 },
  { text: "Выложить мангал из кирпича", l2: "masonry", weight: 30 },
  { text: "Сложить печь", l2: "masonry", weight: 30 },
  { text: "Сложить камин", l2: "masonry", weight: 25 },
  { text: "Услуги каменщика", l2: "masonry", weight: 45 },
  // ── welding — Сварочные работы ──
  { text: "Услуги сварщика", l2: "welding", weight: 60 },
  { text: "Сварщик с выездом", l2: "welding", weight: 50 },
  { text: "Сварить ворота", l2: "welding", weight: 55 },
  { text: "Сварить калитку", l2: "welding", weight: 40 },
  { text: "Отремонтировать ворота сваркой", l2: "welding", weight: 30 },
  { text: "Сварить решётки на окна", l2: "welding", weight: 40 },
  // спорно: навесы есть и в landscape / general-construction; металлический варит сварщик
  { text: "Сварить навес из металла", l2: "welding", weight: 45 },
  { text: "Сварить металлическую лестницу", l2: "welding", weight: 30 },
  { text: "Сварить перила", l2: "welding", weight: 30 },
  { text: "Сварить металлический каркас", l2: "welding", weight: 30 },
  { text: "Сварить трубы", l2: "welding", weight: 30 },
  { text: "Сварить мангал", l2: "welding", weight: 25 },
  { text: "Аргонная сварка", l2: "welding", weight: 20 },
  // ── machinery — Спецтехника ──
  { text: "Заказать экскаватор", l2: "machinery", weight: 55 },
  { text: "Экскаватор-погрузчик на час", l2: "machinery", weight: 40 },
  { text: "Выкопать котлован", l2: "machinery", weight: 45 },
  { text: "Выкопать траншею экскаватором", l2: "machinery", weight: 30 },
  { text: "Спланировать участок трактором", l2: "machinery", weight: 25 },
  { text: "Заказать самосвал", l2: "machinery", weight: 45 },
  // спорно: может быть грузоперевозки; песок и щебень возит самосвал
  { text: "Привезти песок самосвалом", l2: "machinery", weight: 40 },
  { text: "Заказать манипулятор", l2: "machinery", weight: 40 },
  { text: "Заказать автовышку", l2: "machinery", weight: 30 },
  { text: "Ямобур для столбов", l2: "machinery", weight: 25 },
  { text: "Заказать миксер с бетоном", l2: "machinery", weight: 30 },
  { text: "Заказать бетононасос", l2: "machinery", weight: 25 },
  // ── general-construction — Строительство ──
  { text: "Построить частный дом", l2: "general-construction", weight: 60 },
  { text: "Построить дом под ключ", l2: "general-construction", weight: 55 },
  { text: "Возвести коробку дома", l2: "general-construction", weight: 40 },
  { text: "Построить каркасный дом", l2: "general-construction", weight: 30 },
  { text: "Построить второй этаж", l2: "general-construction", weight: 35 },
  { text: "Сделать пристройку к дому", l2: "general-construction", weight: 45 },
  { text: "Построить гараж", l2: "general-construction", weight: 50 },
  // спорно: навесы есть и в landscape; металлический — welding
  { text: "Построить навес для машины", l2: "general-construction", weight: 45 },
  { text: "Построить летнюю кухню", l2: "general-construction", weight: 35 },
  { text: "Построить гостевой дом", l2: "general-construction", weight: 25 },
  { text: "Построить сарай", l2: "general-construction", weight: 30 },
  { text: "Построить хозблок", l2: "general-construction", weight: 25 },
  { text: "Построить садовый домик", l2: "general-construction", weight: 15 },
  { text: "Бригада строителей", l2: "general-construction", weight: 50 },
  // ── drilling-wells — Бурение скважин и колодцы ──
  { text: "Пробурить скважину на воду", l2: "drilling-wells", weight: 70 },
  { text: "Пробурить абиссинскую скважину", l2: "drilling-wells", weight: 15 },
  { text: "Отремонтировать скважину", l2: "drilling-wells", weight: 45 },
  { text: "Почистить скважину", l2: "drilling-wells", weight: 40 },
  { text: "Установить насос в скважину", l2: "drilling-wells", weight: 50 },
  { text: "Заменить насос в скважине", l2: "drilling-wells", weight: 40 },
  { text: "Подключить скважину к дому", l2: "drilling-wells", weight: 45 },
  { text: "Установить кессон", l2: "drilling-wells", weight: 25 },
  { text: "Выкопать колодец", l2: "drilling-wells", weight: 35 },
  { text: "Почистить колодец", l2: "drilling-wells", weight: 30 },
  { text: "Углубить колодец", l2: "drilling-wells", weight: 15 },
  { text: "Сделать анализ воды", l2: "drilling-wells", weight: 20 },
  // ── fences-gates — Заборы и ворота ──
  { text: "Поставить забор", l2: "fences-gates", weight: 70 },
  { text: "Забор из профнастила", l2: "fences-gates", weight: 60 },
  { text: "Поставить забор из сетки-рабицы", l2: "fences-gates", weight: 35 },
  { text: "Забор из евроштакетника", l2: "fences-gates", weight: 30 },
  { text: "Построить кирпичный забор", l2: "fences-gates", weight: 35 },
  { text: "Кованый забор", l2: "fences-gates", weight: 20 },
  { text: "Установить столбы для забора", l2: "fences-gates", weight: 30 },
  { text: "Отремонтировать забор", l2: "fences-gates", weight: 35 },
  { text: "Установить откатные ворота", l2: "fences-gates", weight: 50 },
  { text: "Установить распашные ворота", l2: "fences-gates", weight: 45 },
  { text: "Установить автоматику на ворота", l2: "fences-gates", weight: 40 },
  { text: "Отремонтировать откатные ворота", l2: "fences-gates", weight: 30 },
  // спорно: может и doors / welding; в каталоге ворота — здесь
  { text: "Установить гаражные ворота", l2: "fences-gates", weight: 25 },
  { text: "Установить калитку", l2: "fences-gates", weight: 35 },
  // ── landscape — Благоустройство и ландшафт ──
  { text: "Уложить тротуарную плитку", l2: "landscape", weight: 65 },
  { text: "Уложить брусчатку во дворе", l2: "landscape", weight: 45 },
  { text: "Установить бордюры", l2: "landscape", weight: 35 },
  { text: "Сделать дорожки на участке", l2: "landscape", weight: 40 },
  { text: "Благоустроить двор", l2: "landscape", weight: 50 },
  { text: "Ландшафтный дизайн участка", l2: "landscape", weight: 30 },
  { text: "Положить рулонный газон", l2: "landscape", weight: 30 },
  // спорно: в garden есть «Посадка и уход за газоном»
  { text: "Посеять газон", l2: "landscape", weight: 25 },
  { text: "Оформить клумбы и альпийскую горку", l2: "landscape", weight: 20 },
  { text: "Сделать дренаж на участке", l2: "landscape", weight: 30 },
  // спорно: в garden есть «Полив и капельный полив»
  { text: "Сделать автополив", l2: "landscape", weight: 30 },
  // спорно: могут искать электрика
  { text: "Сделать освещение участка", l2: "landscape", weight: 30 },
  { text: "Построить беседку", l2: "landscape", weight: 45 },
  { text: "Сделать перголу", l2: "landscape", weight: 15 },
  { text: "Сделать детскую площадку", l2: "landscape", weight: 25 },
  // ── baths-pools — Бани, бассейны и хамамы ──
  { text: "Построить баню", l2: "baths-pools", weight: 45 },
  { text: "Отделать баню внутри", l2: "baths-pools", weight: 30 },
  { text: "Отремонтировать баню", l2: "baths-pools", weight: 20 },
  { text: "Установить печь в баню", l2: "baths-pools", weight: 30 },
  { text: "Построить сауну", l2: "baths-pools", weight: 25 },
  { text: "Построить хамам", l2: "baths-pools", weight: 25 },
  { text: "Построить бассейн", l2: "baths-pools", weight: 35 },
  // спорно: укладку мозаики может делать плиточник (tiling)
  { text: "Отделать бассейн мозаикой", l2: "baths-pools", weight: 20 },
  { text: "Гидроизоляция бассейна", l2: "baths-pools", weight: 20 },
  { text: "Почистить бассейн", l2: "baths-pools", weight: 30 },
  { text: "Обслуживание бассейна", l2: "baths-pools", weight: 25 },
  // ── demolition — Демонтаж ──
  { text: "Демонтаж квартиры перед ремонтом", l2: "demolition", weight: 45 },
  { text: "Демонтировать стену", l2: "demolition", weight: 40 },
  { text: "Снести перегородку", l2: "demolition", weight: 40 },
  { text: "Сбить старую плитку", l2: "demolition", weight: 45 },
  { text: "Снять штукатурку со стен", l2: "demolition", weight: 30 },
  { text: "Демонтировать напольное покрытие", l2: "demolition", weight: 25 },
  { text: "Демонтировать стяжку", l2: "demolition", weight: 20 },
  { text: "Демонтировать потолок", l2: "demolition", weight: 20 },
  { text: "Демонтировать старые окна", l2: "demolition", weight: 25 },
  { text: "Демонтировать сантехнику", l2: "demolition", weight: 25 },
  // спорно: часто снимает сантехник вместе с установкой новой
  { text: "Демонтировать старую ванну", l2: "demolition", weight: 30 },
  { text: "Снести старый дом", l2: "demolition", weight: 40 },
  { text: "Снести сарай", l2: "demolition", weight: 25 },
  { text: "Разобрать старую постройку", l2: "demolition", weight: 30 },
  // ── cleaning — Уборка (клининг) ──
  { text: "Генеральная уборка квартиры", l2: "cleaning", weight: 95 },
  { text: "Уборка квартиры", l2: "cleaning", weight: 90 },
  // Как говорят люди (№259, подсказки YouDo): «убраться в …».
  { text: "Убраться в квартире", l2: "cleaning", weight: 88 },
  { text: "Убраться в доме", l2: "cleaning", weight: 70 },
  { text: "Убраться в комнате", l2: "cleaning", weight: 55 },
  { text: "Убраться в офисе", l2: "cleaning", weight: 40 },
  { text: "Убраться в однокомнатной квартире", l2: "cleaning", weight: 45 },
  { text: "Убраться в двухкомнатной квартире", l2: "cleaning", weight: 40 },
  { text: "Уборка комнаты", l2: "cleaning", weight: 40 },
  { text: "Прибраться в квартире", l2: "cleaning", weight: 35 },
  { text: "Регулярная уборка квартиры", l2: "cleaning", weight: 60 },
  { text: "Уборка дома", l2: "cleaning", weight: 75 },
  { text: "Генеральная уборка дома", l2: "cleaning", weight: 70 },
  { text: "Уборка частного дома", l2: "cleaning", weight: 55 },
  { text: "Услуги уборщицы", l2: "cleaning", weight: 50 },
  { text: "Помыть окна", l2: "cleaning", weight: 80 },
  { text: "Мытьё окон", l2: "cleaning", weight: 60 },
  { text: "Мытьё окон в частном доме", l2: "cleaning", weight: 35 },
  { text: "Помыть балкон", l2: "cleaning", weight: 25 },
  { text: "Уборка кухни", l2: "cleaning", weight: 45 },
  { text: "Помыть кухню", l2: "cleaning", weight: 35 },
  { text: "Уборка санузла", l2: "cleaning", weight: 35 },
  { text: "Помыть люстру", l2: "cleaning", weight: 20 },
  { text: "Уборка после праздника", l2: "cleaning", weight: 40 },
  { text: "Уборка после переезда", l2: "cleaning", weight: 30 },
  { text: "Уборка офиса", l2: "cleaning", weight: 45 },
  { text: "Уборка магазина", l2: "cleaning", weight: 25 },
  { text: "Уборка подъезда", l2: "cleaning", weight: 20 },
  { text: "Химчистка дивана", l2: "cleaning", weight: 65 },
  { text: "Химчистка мебели", l2: "cleaning", weight: 45 },
  { text: "Химчистка матраса", l2: "cleaning", weight: 45 },
  { text: "Химчистка кресел", l2: "cleaning", weight: 30 },
  // спорно: стирка ковров в цехе — laundry; химчистка на дому — cleaning (в каталоге «Химчистка ковров»)
  { text: "Химчистка ковра на дому", l2: "cleaning", weight: 50 },
  // ── laundry — Стирка и чистка ──
  { text: "Стирка ковров", l2: "laundry", weight: 65 },
  { text: "Постирать ковёр", l2: "laundry", weight: 50 },
  { text: "Постирать палас", l2: "laundry", weight: 30 },
  { text: "Стирка штор и тюля", l2: "laundry", weight: 45 },
  { text: "Постирать бельё", l2: "laundry", weight: 40 },
  { text: "Постирать одеяла и подушки", l2: "laundry", weight: 30 },
  // спорно: в housekeeping есть «Глажка белья»
  { text: "Погладить одежду", l2: "laundry", weight: 40 },
  { text: "Химчистка одежды", l2: "laundry", weight: 35 },
  { text: "Химчистка пальто", l2: "laundry", weight: 30 },
  { text: "Химчистка пуховика", l2: "laundry", weight: 30 },
  { text: "Почистить обувь", l2: "laundry", weight: 20 },
  { text: "Отремонтировать обувь", l2: "laundry", weight: 30 },
  // ── disposal — Вывоз мусора ──
  { text: "Вывезти мусор", l2: "disposal", weight: 90 },
  { text: "Вывоз мусора", l2: "disposal", weight: 85 },
  { text: "Вывезти строительный мусор", l2: "disposal", weight: 85 },
  { text: "Вывоз строительного мусора", l2: "disposal", weight: 70 },
  { text: "Вывезти мусор после ремонта", l2: "disposal", weight: 65 },
  { text: "Вывезти бытовой мусор", l2: "disposal", weight: 50 },
  { text: "Вывезти мусор с участка", l2: "disposal", weight: 55 },
  { text: "Вывезти мусор с балкона", l2: "disposal", weight: 25 },
  { text: "Вывоз мусора на газели", l2: "disposal", weight: 40 },
  { text: "Заказать контейнер для мусора", l2: "disposal", weight: 35 },
  { text: "Вывезти старую мебель", l2: "disposal", weight: 70 },
  { text: "Вывезти старый диван", l2: "disposal", weight: 45 },
  { text: "Вывезти старую технику", l2: "disposal", weight: 50 },
  { text: "Вывезти старый холодильник", l2: "disposal", weight: 35 },
  { text: "Утилизировать старую технику", l2: "disposal", weight: 30 },
  { text: "Вывезти старые окна и двери", l2: "disposal", weight: 20 },
  { text: "Вывезти ветки", l2: "disposal", weight: 40 },
  { text: "Вывезти траву и листья", l2: "disposal", weight: 35 },
  // спорно: большой объём — спецтехника (machinery, самосвал)
  { text: "Вывезти грунт", l2: "disposal", weight: 40 },
  { text: "Расчистить двор", l2: "disposal", weight: 45 },
  { text: "Расчистить гараж от хлама", l2: "disposal", weight: 35 },
  { text: "Освободить подвал от хлама", l2: "disposal", weight: 25 },
  // ── garden — Сад и участок ──
  { text: "Покосить траву", l2: "garden", weight: 65 },
  { text: "Покос травы триммером", l2: "garden", weight: 35 },
  { text: "Убрать участок", l2: "garden", weight: 45 },
  { text: "Перекопать огород", l2: "garden", weight: 40 },
  { text: "Вспахать огород мотоблоком", l2: "garden", weight: 30 },
  { text: "Прополоть грядки", l2: "garden", weight: 25 },
  { text: "Обрезать деревья", l2: "garden", weight: 45 },
  { text: "Обрезать кусты", l2: "garden", weight: 30 },
  // спорно: в landscape тоже есть «Спил / обрезка деревьев»
  { text: "Спилить дерево", l2: "garden", weight: 55 },
  { text: "Посадить деревья", l2: "garden", weight: 30 },
  { text: "Побелить деревья", l2: "garden", weight: 20 },
  { text: "Уход за газоном", l2: "garden", weight: 25 },
  { text: "Сделать капельный полив", l2: "garden", weight: 25 },
  // спорно: может и pest-control
  { text: "Обработать сад от вредителей", l2: "garden", weight: 30 },
  { text: "Услуги садовника", l2: "garden", weight: 30 },
  // ── pest-control — Дезинфекция и борьба с вредителями ──
  { text: "Обработать от тараканов", l2: "pest-control", weight: 55 },
  { text: "Вывести тараканов", l2: "pest-control", weight: 45 },
  { text: "Обработать от клопов", l2: "pest-control", weight: 50 },
  { text: "Обработать от блох", l2: "pest-control", weight: 30 },
  { text: "Обработать от муравьёв", l2: "pest-control", weight: 25 },
  { text: "Обработать от комаров", l2: "pest-control", weight: 20 },
  { text: "Обработать участок от клещей", l2: "pest-control", weight: 35 },
  { text: "Уничтожить осиное гнездо", l2: "pest-control", weight: 25 },
  { text: "Избавиться от мышей", l2: "pest-control", weight: 40 },
  { text: "Избавиться от крыс", l2: "pest-control", weight: 35 },
  { text: "Дезинфекция квартиры", l2: "pest-control", weight: 40 },
  { text: "Дезинсекция дома", l2: "pest-control", weight: 25 },
  { text: "Обработать от плесени", l2: "pest-control", weight: 35 },
  // ── cleaning-post-renovation — Уборка после ремонта ──
  { text: "Уборка после ремонта", l2: "cleaning-post-renovation", weight: 85 },
  { text: "Убраться после ремонта", l2: "cleaning-post-renovation", weight: 50 },
  { text: "Генеральная уборка после ремонта", l2: "cleaning-post-renovation", weight: 60 },
  { text: "Уборка после капитального ремонта", l2: "cleaning-post-renovation", weight: 35 },
  { text: "Уборка после косметического ремонта", l2: "cleaning-post-renovation", weight: 25 },
  { text: "Уборка дома после стройки", l2: "cleaning-post-renovation", weight: 45 },
  { text: "Помыть окна после ремонта", l2: "cleaning-post-renovation", weight: 45 },
  { text: "Отмыть краску и цемент", l2: "cleaning-post-renovation", weight: 30 },
  { text: "Отмыть плитку после ремонта", l2: "cleaning-post-renovation", weight: 25 },
  { text: "Удалить строительную пыль", l2: "cleaning-post-renovation", weight: 30 },
  { text: "Уборка перед заселением", l2: "cleaning-post-renovation", weight: 40 },
  // ── housekeeping — Помощь по хозяйству ──
  { text: "Домработница", l2: "housekeeping", weight: 50 },
  { text: "Помощь по хозяйству", l2: "housekeeping", weight: 45 },
  { text: "Помощница по дому на день", l2: "housekeeping", weight: 30 },
  { text: "Помощь с готовкой", l2: "housekeeping", weight: 35 },
  { text: "Помочь с готовкой к празднику", l2: "housekeeping", weight: 30 },
  { text: "Повар на дом", l2: "housekeeping", weight: 30 },
  // спорно: в laundry есть «Глажка одежды и белья»
  { text: "Глажка белья", l2: "housekeeping", weight: 35 },
  // спорно: может и caregivers (сиделка)
  { text: "Помощь пожилым по дому", l2: "housekeeping", weight: 35 },
  // ── caregivers — Няни и сиделки ──
  { text: "Няня для ребёнка", l2: "caregivers", weight: 50 },
  { text: "Няня на час", l2: "caregivers", weight: 40 },
  { text: "Няня для грудничка", l2: "caregivers", weight: 25 },
  { text: "Посидеть с ребёнком вечером", l2: "caregivers", weight: 30 },
  { text: "Сиделка для пожилого человека", l2: "caregivers", weight: 45 },
  { text: "Сиделка для лежачего больного", l2: "caregivers", weight: 35 },
  { text: "Сиделка в больницу", l2: "caregivers", weight: 30 },
  { text: "Уход за пожилым человеком", l2: "caregivers", weight: 35 },
  // ── furniture — Мебель и сборка ──
  // спорно: в handyman есть «Сборка мебели»; сборщик мебели — здесь
  { text: "Собрать мебель", l2: "furniture", weight: 90 },
  { text: "Собрать шкаф", l2: "furniture", weight: 85 },
  { text: "Собрать шкаф-купе", l2: "furniture", weight: 55 },
  { text: "Собрать кухню", l2: "furniture", weight: 70 },
  { text: "Собрать кровать", l2: "furniture", weight: 65 },
  { text: "Собрать детскую кровать", l2: "furniture", weight: 30 },
  { text: "Собрать комод", l2: "furniture", weight: 40 },
  { text: "Собрать стол и стулья", l2: "furniture", weight: 35 },
  { text: "Разобрать шкаф", l2: "furniture", weight: 40 },
  // спорно: может и мастер на час
  { text: "Повесить кухонные шкафы", l2: "furniture", weight: 45 },
  { text: "Установить столешницу", l2: "furniture", weight: 35 },
  // спорно: подключение — appliance-repair; встраивание в корпус — сборщик
  { text: "Встроить технику в кухню", l2: "furniture", weight: 30 },
  { text: "Кухня на заказ", l2: "furniture", weight: 60 },
  { text: "Изготовить мебель на заказ", l2: "furniture", weight: 50 },
  { text: "Изготовить шкаф-купе на заказ", l2: "furniture", weight: 45 },
  { text: "Сделать гардеробную", l2: "furniture", weight: 35 },
  { text: "Мебель из массива на заказ", l2: "furniture", weight: 20 },
  { text: "Заменить фасады кухни", l2: "furniture", weight: 30 },
  { text: "Отремонтировать диван", l2: "furniture", weight: 40 },
  { text: "Перетянуть диван", l2: "furniture", weight: 40 },
  { text: "Перетянуть стулья", l2: "furniture", weight: 25 },
  { text: "Отремонтировать шкаф", l2: "furniture", weight: 30 },
  { text: "Отреставрировать мебель", l2: "furniture", weight: 25 },
  // ── curtains-blinds — Шторы и жалюзи ──
  { text: "Сшить шторы на заказ", l2: "curtains-blinds", weight: 45 },
  // спорно: могут отнести в ателье
  { text: "Подшить шторы", l2: "curtains-blinds", weight: 30 },
  { text: "Установить потолочный карниз", l2: "curtains-blinds", weight: 30 },
  { text: "Установить электрокарниз", l2: "curtains-blinds", weight: 10 },
  { text: "Установить жалюзи", l2: "curtains-blinds", weight: 45 },
  { text: "Установить вертикальные жалюзи", l2: "curtains-blinds", weight: 25 },
  { text: "Установить жалюзи день-ночь", l2: "curtains-blinds", weight: 20 },
  { text: "Установить рулонные шторы", l2: "curtains-blinds", weight: 45 },
  { text: "Установить римские шторы", l2: "curtains-blinds", weight: 25 },
  { text: "Установить плиссе", l2: "curtains-blinds", weight: 15 },
  { text: "Установить рольставни", l2: "curtains-blinds", weight: 25 },
  { text: "Отремонтировать жалюзи", l2: "curtains-blinds", weight: 25 },
  { text: "Затонировать окна плёнкой", l2: "curtains-blinds", weight: 25 },
  // ── interior-design — Дизайн интерьера ──
  { text: "Дизайн-проект квартиры", l2: "interior-design", weight: 50 },
  { text: "Дизайн-проект дома", l2: "interior-design", weight: 40 },
  { text: "Дизайн интерьера кухни", l2: "interior-design", weight: 35 },
  { text: "Дизайн ванной комнаты", l2: "interior-design", weight: 25 },
  { text: "Дизайн коммерческого помещения", l2: "interior-design", weight: 15 },
  { text: "Сделать 3D-визуализацию интерьера", l2: "interior-design", weight: 25 },
  { text: "Подобрать материалы для ремонта", l2: "interior-design", weight: 25 },
  { text: "Авторский надзор за ремонтом", l2: "interior-design", weight: 15 },
  { text: "Консультация дизайнера интерьера", l2: "interior-design", weight: 30 },
  // спорно: согласование перепланировки — юристы / документы
  { text: "Перепланировка квартиры", l2: "interior-design", weight: 30 },
  // ── tension-ceilings — Натяжные потолки ──
  { text: "Установить натяжной потолок", l2: "tension-ceilings", weight: 75 },
  { text: "Натяжные потолки под ключ", l2: "tension-ceilings", weight: 45 },
  { text: "Натяжной потолок с подсветкой", l2: "tension-ceilings", weight: 35 },
  { text: "Парящий натяжной потолок", l2: "tension-ceilings", weight: 20 },
  { text: "Многоуровневый натяжной потолок", l2: "tension-ceilings", weight: 25 },
  { text: "Тканевый натяжной потолок", l2: "tension-ceilings", weight: 20 },
  { text: "Натяжной потолок с фотопечатью", l2: "tension-ceilings", weight: 15 },
  { text: "Натяжной потолок звёздное небо", l2: "tension-ceilings", weight: 15 },
  { text: "Отремонтировать натяжной потолок", l2: "tension-ceilings", weight: 30 },
  { text: "Слить воду с натяжного потолка", l2: "tension-ceilings", weight: 30 },
  { text: "Заменить полотно натяжного потолка", l2: "tension-ceilings", weight: 20 },
  // спорно: может и электрик
  { text: "Установить светильники в натяжной потолок", l2: "tension-ceilings", weight: 30 },
  // ── ceilings — Подвесные потолки ──
  { text: "Сделать подвесной потолок", l2: "ceilings", weight: 35 },
  { text: "Подвесной потолок в офисе", l2: "ceilings", weight: 20 },
  { text: "Установить потолок Армстронг", l2: "ceilings", weight: 30 },
  { text: "Установить реечный потолок", l2: "ceilings", weight: 30 },
  { text: "Установить кассетный потолок", l2: "ceilings", weight: 15 },
  { text: "Сделать деревянный потолок", l2: "ceilings", weight: 25 },
  { text: "Обшить потолок вагонкой", l2: "ceilings", weight: 25 },
  // спорно: термин «пвх потолок» в каталоге — у tension-ceilings, но панели ПВХ — подвесной/обшивной
  { text: "Обшить потолок панелями ПВХ", l2: "ceilings", weight: 35 },
  // ── locks-security — Замки и безопасность ──
  { text: "Вскрыть замок", l2: "locks-security", weight: 60 },
  { text: "Открыть дверь без ключа", l2: "locks-security", weight: 55 },
  { text: "Заменить замок", l2: "locks-security", weight: 60 },
  { text: "Поменять замок во входной двери", l2: "locks-security", weight: 45 },
  { text: "Заменить личинку замка", l2: "locks-security", weight: 40 },
  { text: "Врезать замок", l2: "locks-security", weight: 45 },
  { text: "Перекодировать замок", l2: "locks-security", weight: 25 },
  { text: "Установить умный замок", l2: "locks-security", weight: 20 },
  { text: "Вскрыть сейф", l2: "locks-security", weight: 20 },
  // спорно: отдельной авто-категории для вскрытия нет; вскрывает тот же мастер
  { text: "Вскрыть замок автомобиля", l2: "locks-security", weight: 30 },
  // ── appliance-repair — Ремонт бытовой техники ──
  { text: "Ремонт бытовой техники", l2: "appliance-repair", weight: 60 },
  { text: "Отремонтировать стиральную машину", l2: "appliance-repair", weight: 90 },
  { text: "Починить стиральную машину", l2: "appliance-repair", weight: 85 },
  { text: "Отремонтировать холодильник", l2: "appliance-repair", weight: 85 },
  { text: "Починить холодильник", l2: "appliance-repair", weight: 65 },
  { text: "Заправить холодильник фреоном", l2: "appliance-repair", weight: 25 },
  { text: "Отремонтировать морозильную камеру", l2: "appliance-repair", weight: 25 },
  { text: "Отремонтировать посудомоечную машину", l2: "appliance-repair", weight: 55 },
  { text: "Отремонтировать сушильную машину", l2: "appliance-repair", weight: 20 },
  { text: "Отремонтировать газовую плиту", l2: "appliance-repair", weight: 50 },
  { text: "Отремонтировать электроплиту", l2: "appliance-repair", weight: 40 },
  { text: "Отремонтировать варочную панель", l2: "appliance-repair", weight: 35 },
  { text: "Отремонтировать духовку", l2: "appliance-repair", weight: 45 },
  { text: "Отремонтировать микроволновку", l2: "appliance-repair", weight: 40 },
  { text: "Отремонтировать телевизор", l2: "appliance-repair", weight: 55 },
  { text: "Починить телевизор", l2: "appliance-repair", weight: 40 },
  { text: "Отремонтировать пылесос", l2: "appliance-repair", weight: 30 },
  { text: "Отремонтировать кофемашину", l2: "appliance-repair", weight: 20 },
  { text: "Отремонтировать мультиварку", l2: "appliance-repair", weight: 15 },
  { text: "Отремонтировать швейную машину", l2: "appliance-repair", weight: 20 },
  { text: "Отремонтировать мелкую бытовую технику", l2: "appliance-repair", weight: 30 },
  // спорно: в plumbing есть «Подключение стиральной машины»
  { text: "Установить стиральную машину", l2: "appliance-repair", weight: 55 },
  // спорно: как стиральная машина
  { text: "Установить посудомоечную машину", l2: "appliance-repair", weight: 40 },
  { text: "Установить духовой шкаф", l2: "appliance-repair", weight: 35 },
  { text: "Установить кухонную вытяжку", l2: "appliance-repair", weight: 40 },
  // ── satellite-tv — Спутниковое ТВ и антенны ──
  { text: "Установить спутниковую антенну", l2: "satellite-tv", weight: 55 },
  { text: "Настроить спутниковую тарелку", l2: "satellite-tv", weight: 50 },
  { text: "Отремонтировать спутниковую антенну", l2: "satellite-tv", weight: 25 },
  { text: "Установить эфирную антенну", l2: "satellite-tv", weight: 35 },
  { text: "Установить антенну на крыше", l2: "satellite-tv", weight: 20 },
  { text: "Настроить цифровое телевидение", l2: "satellite-tv", weight: 40 },
  { text: "Настроить каналы на телевизоре", l2: "satellite-tv", weight: 40 },
  { text: "Подключить интернет-телевидение", l2: "satellite-tv", weight: 25 },
  { text: "Установить усилитель сигнала", l2: "satellite-tv", weight: 20 },
  // ── security-systems — Видеонаблюдение и охрана ──
  { text: "Установить видеонаблюдение", l2: "security-systems", weight: 65 },
  { text: "Видеонаблюдение для частного дома", l2: "security-systems", weight: 40 },
  { text: "Установить камеры видеонаблюдения во дворе", l2: "security-systems", weight: 40 },
  { text: "Установить видеонаблюдение в магазине", l2: "security-systems", weight: 25 },
  { text: "Настроить видеонаблюдение с телефона", l2: "security-systems", weight: 30 },
  { text: "Обслуживание видеонаблюдения", l2: "security-systems", weight: 15 },
  { text: "Установить домофон", l2: "security-systems", weight: 45 },
  { text: "Установить видеодомофон", l2: "security-systems", weight: 40 },
  { text: "Отремонтировать домофон", l2: "security-systems", weight: 25 },
  { text: "Установить охранную сигнализацию", l2: "security-systems", weight: 40 },
  { text: "Установить пожарную сигнализацию", l2: "security-systems", weight: 20 },
  { text: "Установить контроль доступа", l2: "security-systems", weight: 15 },
  // ── handyman — Мастер на час ──
  { text: "Мастер на час", l2: "handyman", weight: 95 },
  { text: "Муж на час", l2: "handyman", weight: 70 },
  { text: "Мастер на все руки", l2: "handyman", weight: 50 },
  { text: "Мелкий ремонт по дому", l2: "handyman", weight: 70 },
  { text: "Мелкий ремонт в квартире", l2: "handyman", weight: 50 },
  { text: "Повесить телевизор на стену", l2: "handyman", weight: 80 },
  { text: "Повесить полку", l2: "handyman", weight: 70 },
  { text: "Повесить зеркало", l2: "handyman", weight: 50 },
  { text: "Повесить картину", l2: "handyman", weight: 45 },
  { text: "Повесить вешалку", l2: "handyman", weight: 30 },
  { text: "Повесить турник", l2: "handyman", weight: 30 },
  { text: "Повесить сушилку для белья", l2: "handyman", weight: 30 },
  // спорно: в curtains-blinds есть «Установка карнизов»; вешает обычно мастер на час
  { text: "Повесить шторы", l2: "handyman", weight: 60 },
  // спорно: как «Повесить шторы»
  { text: "Повесить карниз", l2: "handyman", weight: 55 },
  { text: "Просверлить отверстия в стене", l2: "handyman", weight: 40 },
  { text: "Заделать щели", l2: "handyman", weight: 35 },
  { text: "Заделать трещину в стене", l2: "handyman", weight: 35 },
  // спорно: может и doors
  { text: "Отрегулировать межкомнатную дверь", l2: "handyman", weight: 35 },
  { text: "Отрегулировать дверцы шкафа", l2: "handyman", weight: 25 },
  { text: "Заменить ручки на дверях", l2: "handyman", weight: 30 },
  { text: "Заменить лампочки", l2: "handyman", weight: 30 },
  { text: "Обновить герметик в ванной", l2: "handyman", weight: 25 },
  { text: "Установить бортик в ванной", l2: "handyman", weight: 25 },
  // спорно: может и plumbing
  { text: "Мелкий ремонт сантехники", l2: "handyman", weight: 40 },
  // спорно: может и electrical
  { text: "Мелкие электромонтажные работы", l2: "handyman", weight: 35 },
  // ── laborers — Разнорабочие ──
  { text: "Разнорабочий на день", l2: "laborers", weight: 60 },
  { text: "Разнорабочие на час", l2: "laborers", weight: 45 },
  { text: "Бригада разнорабочих", l2: "laborers", weight: 35 },
  { text: "Подсобник на стройку", l2: "laborers", weight: 40 },
  // спорно: может и movers (грузчики); в каталоге «Погрузка и разгрузка» — здесь
  { text: "Разгрузить машину", l2: "laborers", weight: 50 },
  { text: "Разгрузить стройматериалы", l2: "laborers", weight: 45 },
  { text: "Поднять стройматериалы на этаж", l2: "laborers", weight: 30 },
  { text: "Выкопать траншею", l2: "laborers", weight: 45 },
  { text: "Выкопать яму", l2: "laborers", weight: 35 },
  { text: "Земляные работы вручную", l2: "laborers", weight: 30 },
  { text: "Перекидать песок", l2: "laborers", weight: 25 },
  // спорно: может garden («Уборка участка») или disposal
  { text: "Расчистить участок", l2: "laborers", weight: 40 },
  // ── cargo-transport — Грузоперевозки ──
  { text: "Газель с водителем", l2: "cargo-transport", weight: 80 },
  { text: "Грузовое такси", l2: "cargo-transport", weight: 50 },
  { text: "Грузовик с водителем", l2: "cargo-transport", weight: 40 },
  { text: "Перевезти вещи", l2: "cargo-transport", weight: 80 },
  { text: "Перевезти груз", l2: "cargo-transport", weight: 55 },
  { text: "Перевезти мебель", l2: "cargo-transport", weight: 70 },
  { text: "Перевезти диван", l2: "cargo-transport", weight: 50 },
  { text: "Перевезти холодильник", l2: "cargo-transport", weight: 55 },
  { text: "Перевезти стиральную машину", l2: "cargo-transport", weight: 40 },
  { text: "Перевезти бытовую технику", l2: "cargo-transport", weight: 40 },
  { text: "Перевезти пианино", l2: "cargo-transport", weight: 15 },
  { text: "Перевезти стройматериалы", l2: "cargo-transport", weight: 55 },
  { text: "Привезти стройматериалы с рынка", l2: "cargo-transport", weight: 35 },
  { text: "Доставить мебель из магазина", l2: "cargo-transport", weight: 50 },
  { text: "Перевезти вещи в другой город", l2: "cargo-transport", weight: 50 },
  { text: "Междугородняя перевозка груза", l2: "cargo-transport", weight: 35 },
  { text: "Перевезти вещи на дачу", l2: "cargo-transport", weight: 25 },
  { text: "Перевезти скот", l2: "cargo-transport", weight: 25 },
  // ── movers — Грузчики и переезды ──
  { text: "Грузчики на переезд", l2: "movers", weight: 80 },
  // спорно: может cargo-transport; переезд квартиры с погрузкой — movers
  { text: "Перевезти вещи на новую квартиру", l2: "movers", weight: 85 },
  { text: "Переезд квартиры", l2: "movers", weight: 75 },
  { text: "Переезд в новый дом", l2: "movers", weight: 55 },
  { text: "Переезд офиса", l2: "movers", weight: 35 },
  { text: "Помочь с переездом", l2: "movers", weight: 50 },
  { text: "Газель с грузчиками", l2: "movers", weight: 65 },
  { text: "Грузчики на час", l2: "movers", weight: 60 },
  // спорно: может laborers («Погрузка и разгрузка»)
  { text: "Грузчики для разгрузки фуры", l2: "movers", weight: 30 },
  { text: "Поднять мебель на этаж", l2: "movers", weight: 45 },
  { text: "Поднять холодильник на этаж", l2: "movers", weight: 35 },
  { text: "Спустить технику с этажа", l2: "movers", weight: 35 },
  { text: "Перенести мебель внутри дома", l2: "movers", weight: 25 },
  { text: "Разобрать и собрать мебель при переезде", l2: "movers", weight: 35 },
  { text: "Упаковать вещи для переезда", l2: "movers", weight: 30 },
  { text: "Погрузить вещи в контейнер", l2: "movers", weight: 20 },
  // ── tow-truck — Эвакуатор ──
  { text: "Вызвать эвакуатор", l2: "tow-truck", weight: 75 },
  { text: "Эвакуировать автомобиль", l2: "tow-truck", weight: 55 },
  { text: "Эвакуировать машину после ДТП", l2: "tow-truck", weight: 40 },
  { text: "Перевезти машину на эвакуаторе", l2: "tow-truck", weight: 40 },
  { text: "Эвакуатор в другой город", l2: "tow-truck", weight: 35 },
  { text: "Перевезти мотоцикл", l2: "tow-truck", weight: 20 },
  { text: "Перевезти спецтехнику", l2: "tow-truck", weight: 25 },
  // спорно: прикурить или поменять колесо — auto-electric / tire-service
  { text: "Техпомощь на дороге", l2: "tow-truck", weight: 30 },
  // ── courier-delivery — Доставка документов и посылок ──
  { text: "Доставить документы", l2: "courier-delivery", weight: 50 },
  { text: "Доставить посылку", l2: "courier-delivery", weight: 50 },
  { text: "Забрать посылку с пункта выдачи", l2: "courier-delivery", weight: 35 },
  { text: "Отправить посылку в другой город", l2: "courier-delivery", weight: 30 },
  { text: "Срочная доставка по городу", l2: "courier-delivery", weight: 40 },
  { text: "Курьер на день", l2: "courier-delivery", weight: 30 },
  { text: "Доставить цветы", l2: "courier-delivery", weight: 30 },
  { text: "Отвезти ключи", l2: "courier-delivery", weight: 20 },
  // ── buy-deliver — Купить и доставить ──
  { text: "Купить и привезти продукты", l2: "buy-deliver", weight: 55 },
  { text: "Купить лекарства в аптеке", l2: "buy-deliver", weight: 45 },
  { text: "Купить и привезти из магазина", l2: "buy-deliver", weight: 35 },
  // спорно: большой объём — cargo-transport
  { text: "Купить и привезти стройматериалы", l2: "buy-deliver", weight: 35 },
  { text: "Купить и привезти запчасти", l2: "buy-deliver", weight: 25 },
  { text: "Привезти воду в бутылях", l2: "buy-deliver", weight: 25 },
  { text: "Купить и привезти подарок", l2: "buy-deliver", weight: 20 },
  // ── food-delivery — Доставка еды ──
  { text: "Доставить еду из кафе", l2: "food-delivery", weight: 45 },
  { text: "Привезти еду из ресторана", l2: "food-delivery", weight: 30 },
  { text: "Доставка обедов в офис", l2: "food-delivery", weight: 35 },
  { text: "Доставить обед домой", l2: "food-delivery", weight: 30 },
  { text: "Доставить готовую еду", l2: "food-delivery", weight: 30 },
  { text: "Доставка домашней еды", l2: "food-delivery", weight: 25 },
  { text: "Доставить торт", l2: "food-delivery", weight: 20 },
  // ── pc-repair — Компьютерная помощь ──
  { text: "Компьютерная помощь", l2: "pc-repair", weight: 75 },
  { text: "Компьютерный мастер на дом", l2: "pc-repair", weight: 50 },
  { text: "Отремонтировать компьютер", l2: "pc-repair", weight: 80 },
  { text: "Починить компьютер", l2: "pc-repair", weight: 60 },
  { text: "Компьютер не включается", l2: "pc-repair", weight: 45 },
  { text: "Собрать компьютер", l2: "pc-repair", weight: 35 },
  { text: "Апгрейд компьютера", l2: "pc-repair", weight: 25 },
  { text: "Почистить компьютер от пыли", l2: "pc-repair", weight: 35 },
  { text: "Отремонтировать ноутбук", l2: "pc-repair", weight: 85 },
  { text: "Починить ноутбук", l2: "pc-repair", weight: 60 },
  { text: "Почистить ноутбук от пыли", l2: "pc-repair", weight: 50 },
  { text: "Заменить экран на ноутбуке", l2: "pc-repair", weight: 40 },
  { text: "Заменить клавиатуру на ноутбуке", l2: "pc-repair", weight: 25 },
  { text: "Отремонтировать телефон", l2: "pc-repair", weight: 85 },
  { text: "Починить телефон", l2: "pc-repair", weight: 60 },
  { text: "Заменить экран на телефоне", l2: "pc-repair", weight: 70 },
  { text: "Заменить стекло на телефоне", l2: "pc-repair", weight: 45 },
  { text: "Заменить аккумулятор в телефоне", l2: "pc-repair", weight: 50 },
  { text: "Заменить разъём зарядки телефона", l2: "pc-repair", weight: 35 },
  { text: "Настроить новый телефон", l2: "pc-repair", weight: 30 },
  { text: "Отремонтировать планшет", l2: "pc-repair", weight: 40 },
  { text: "Переустановить систему на компьютере", l2: "pc-repair", weight: 55 },
  { text: "Установить программы", l2: "pc-repair", weight: 40 },
  { text: "Удалить вирусы с компьютера", l2: "pc-repair", weight: 45 },
  { text: "Восстановить удалённые файлы", l2: "pc-repair", weight: 30 },
  { text: "Настроить роутер", l2: "pc-repair", weight: 55 },
  { text: "Настроить интернет дома", l2: "pc-repair", weight: 50 },
  { text: "Провести интернет-кабель", l2: "pc-repair", weight: 30 },
  { text: "Настроить принтер", l2: "pc-repair", weight: 35 },
  { text: "Отремонтировать принтер", l2: "pc-repair", weight: 30 },
  // ── car-repair — Автосервис и ремонт ──
  { text: "Отремонтировать машину", l2: "car-repair", weight: 75 },
  { text: "Починить машину", l2: "car-repair", weight: 60 },
  { text: "Автомеханик с выездом", l2: "car-repair", weight: 40 },
  { text: "Диагностика автомобиля", l2: "car-repair", weight: 70 },
  { text: "Компьютерная диагностика автомобиля", l2: "car-repair", weight: 45 },
  { text: "Заменить масло в двигателе", l2: "car-repair", weight: 65 },
  { text: "Заменить фильтры в машине", l2: "car-repair", weight: 30 },
  { text: "Заменить свечи зажигания", l2: "car-repair", weight: 25 },
  { text: "Отремонтировать двигатель", l2: "car-repair", weight: 55 },
  { text: "Заменить ремень ГРМ", l2: "car-repair", weight: 40 },
  { text: "Отремонтировать ходовую", l2: "car-repair", weight: 55 },
  { text: "Заменить амортизаторы", l2: "car-repair", weight: 40 },
  { text: "Заменить тормозные колодки", l2: "car-repair", weight: 50 },
  { text: "Прокачать тормоза", l2: "car-repair", weight: 25 },
  { text: "Отремонтировать коробку передач", l2: "car-repair", weight: 40 },
  { text: "Заменить сцепление", l2: "car-repair", weight: 40 },
  { text: "Отремонтировать рулевую рейку", l2: "car-repair", weight: 30 },
  { text: "Отремонтировать глушитель", l2: "car-repair", weight: 30 },
  { text: "Отремонтировать радиатор машины", l2: "car-repair", weight: 20 },
  // спорно: часто делают на шиномонтаже (tire-service)
  { text: "Сделать развал-схождение", l2: "car-repair", weight: 45 },
  // спорно: может auto-electric
  { text: "Заправить кондиционер в машине", l2: "car-repair", weight: 35 },
  { text: "Установить газовое оборудование на машину", l2: "car-repair", weight: 30 },
  { text: "Подготовить машину к техосмотру", l2: "car-repair", weight: 25 },
  // ── auto-electric — Автоэлектрик ──
  { text: "Машина не заводится", l2: "auto-electric", weight: 55 },
  { text: "Услуги автоэлектрика", l2: "auto-electric", weight: 45 },
  { text: "Прикурить автомобиль", l2: "auto-electric", weight: 35 },
  { text: "Заменить аккумулятор в машине", l2: "auto-electric", weight: 35 },
  { text: "Отремонтировать проводку в машине", l2: "auto-electric", weight: 35 },
  { text: "Заменить генератор", l2: "auto-electric", weight: 30 },
  { text: "Отремонтировать стартер", l2: "auto-electric", weight: 30 },
  { text: "Установить автосигнализацию", l2: "auto-electric", weight: 45 },
  { text: "Установить магнитолу", l2: "auto-electric", weight: 30 },
  { text: "Установить камеру заднего вида", l2: "auto-electric", weight: 30 },
  { text: "Установить парктроник", l2: "auto-electric", weight: 20 },
  { text: "Отремонтировать фары", l2: "auto-electric", weight: 20 },
  // ── tire-service — Шиномонтаж ──
  { text: "Поменять резину", l2: "tire-service", weight: 60 },
  { text: "Сезонная замена шин", l2: "tire-service", weight: 50 },
  { text: "Выездной шиномонтаж", l2: "tire-service", weight: 45 },
  { text: "Отремонтировать прокол колеса", l2: "tire-service", weight: 45 },
  { text: "Заклеить колесо", l2: "tire-service", weight: 30 },
  { text: "Заменить колесо", l2: "tire-service", weight: 40 },
  { text: "Отбалансировать колёса", l2: "tire-service", weight: 35 },
  { text: "Отремонтировать диски", l2: "tire-service", weight: 20 },
  { text: "Шиномонтаж грузового авто", l2: "tire-service", weight: 15 },
  // ── body-repair — Кузовной ремонт и покраска ──
  { text: "Кузовной ремонт после ДТП", l2: "body-repair", weight: 45 },
  { text: "Убрать вмятину", l2: "body-repair", weight: 50 },
  { text: "Удаление вмятин без покраски", l2: "body-repair", weight: 30 },
  { text: "Убрать царапины на машине", l2: "body-repair", weight: 40 },
  { text: "Устранить ржавчину на кузове", l2: "body-repair", weight: 25 },
  { text: "Покрасить машину", l2: "body-repair", weight: 45 },
  { text: "Покрасить бампер", l2: "body-repair", weight: 40 },
  { text: "Отремонтировать бампер", l2: "body-repair", weight: 35 },
  { text: "Покрасить диски", l2: "body-repair", weight: 20 },
  { text: "Отполировать машину", l2: "body-repair", weight: 40 },
  // спорно: отдельной категории автостёкол в каталоге нет
  { text: "Заменить лобовое стекло", l2: "body-repair", weight: 30 },
  // ── car-wash — Автомойка и химчистка ──
  { text: "Помыть машину", l2: "car-wash", weight: 50 },
  { text: "Выездная мойка автомобиля", l2: "car-wash", weight: 40 },
  { text: "Помыть двигатель", l2: "car-wash", weight: 20 },
  { text: "Химчистка салона", l2: "car-wash", weight: 55 },
  { text: "Почистить сиденья в машине", l2: "car-wash", weight: 25 },
  { text: "Химчистка потолка в машине", l2: "car-wash", weight: 15 },
  // спорно: детейлинг; полировка в каталоге — body-repair
  { text: "Нанести керамику на кузов", l2: "car-wash", weight: 15 },
  // ── school-subjects — Школьные предметы ──
  { text: "Репетитор по математике", l2: "school-subjects", weight: 85 },
  { text: "Подтянуть ребёнка по математике", l2: "school-subjects", weight: 40 },
  { text: "Репетитор по алгебре", l2: "school-subjects", weight: 25 },
  { text: "Репетитор по геометрии", l2: "school-subjects", weight: 20 },
  { text: "Репетитор по русскому языку", l2: "school-subjects", weight: 70 },
  { text: "Репетитор по литературе", l2: "school-subjects", weight: 20 },
  { text: "Репетитор по физике", l2: "school-subjects", weight: 45 },
  { text: "Репетитор по химии", l2: "school-subjects", weight: 45 },
  { text: "Репетитор по биологии", l2: "school-subjects", weight: 35 },
  { text: "Репетитор по истории", l2: "school-subjects", weight: 25 },
  { text: "Репетитор по обществознанию", l2: "school-subjects", weight: 25 },
  { text: "Репетитор по географии", l2: "school-subjects", weight: 15 },
  { text: "Репетитор по информатике", l2: "school-subjects", weight: 30 },
  { text: "Репетитор по ингушскому языку", l2: "school-subjects", weight: 25 },
  { text: "Репетитор для начальной школы", l2: "school-subjects", weight: 50 },
  { text: "Подготовить ребёнка к школе", l2: "school-subjects", weight: 40 },
  { text: "Научить ребёнка читать", l2: "school-subjects", weight: 35 },
  { text: "Помочь с домашним заданием", l2: "school-subjects", weight: 50 },
  // ── exam-prep — Подготовка к ЕГЭ и ОГЭ ──
  { text: "Подготовка к ЕГЭ", l2: "exam-prep", weight: 50 },
  { text: "Подготовка к ОГЭ", l2: "exam-prep", weight: 40 },
  { text: "Подготовка к ЕГЭ по математике", l2: "exam-prep", weight: 60 },
  { text: "Подготовка к ЕГЭ по русскому языку", l2: "exam-prep", weight: 55 },
  { text: "Подготовка к ЕГЭ по биологии", l2: "exam-prep", weight: 35 },
  { text: "Подготовка к ЕГЭ по химии", l2: "exam-prep", weight: 30 },
  { text: "Подготовка к ЕГЭ по физике", l2: "exam-prep", weight: 25 },
  { text: "Подготовка к ЕГЭ по обществознанию", l2: "exam-prep", weight: 30 },
  { text: "Подготовка к ЕГЭ по истории", l2: "exam-prep", weight: 20 },
  { text: "Подготовка к ЕГЭ по информатике", l2: "exam-prep", weight: 20 },
  // спорно: может languages
  { text: "Подготовка к ЕГЭ по английскому", l2: "exam-prep", weight: 25 },
  { text: "Подготовка к ОГЭ по математике", l2: "exam-prep", weight: 50 },
  { text: "Подготовка к ОГЭ по русскому языку", l2: "exam-prep", weight: 45 },
  { text: "Подготовка к итоговому сочинению", l2: "exam-prep", weight: 15 },
  // ── languages — Иностранные языки ──
  { text: "Репетитор по английскому языку", l2: "languages", weight: 70 },
  { text: "Английский для ребёнка", l2: "languages", weight: 40 },
  { text: "Английский для взрослых", l2: "languages", weight: 30 },
  { text: "Разговорный английский", l2: "languages", weight: 35 },
  { text: "Репетитор по арабскому языку", l2: "languages", weight: 50 },
  { text: "Арабский язык для начинающих", l2: "languages", weight: 30 },
  { text: "Репетитор по турецкому языку", l2: "languages", weight: 20 },
  { text: "Репетитор по немецкому языку", l2: "languages", weight: 20 },
  { text: "Репетитор по французскому языку", l2: "languages", weight: 15 },
  // ── driving-instructor — Автоинструкторы ──
  { text: "Уроки вождения", l2: "driving-instructor", weight: 55 },
  { text: "Научиться водить машину", l2: "driving-instructor", weight: 50 },
  { text: "Уроки вождения на автомате", l2: "driving-instructor", weight: 25 },
  { text: "Автоинструктор на своей машине", l2: "driving-instructor", weight: 25 },
  { text: "Восстановить навыки вождения", l2: "driving-instructor", weight: 30 },
  { text: "Подготовиться к экзамену в ГИБДД", l2: "driving-instructor", weight: 35 },
  { text: "Научиться парковаться", l2: "driving-instructor", weight: 20 },
  // ── lawyers — Юристы ──
  { text: "Консультация юриста", l2: "lawyers", weight: 65 },
  { text: "Составить договор", l2: "lawyers", weight: 50 },
  { text: "Составить исковое заявление", l2: "lawyers", weight: 35 },
  { text: "Составить претензию", l2: "lawyers", weight: 25 },
  { text: "Представительство в суде", l2: "lawyers", weight: 40 },
  { text: "Юрист по наследству", l2: "lawyers", weight: 35 },
  { text: "Юрист по земельным вопросам", l2: "lawyers", weight: 35 },
  { text: "Юрист по семейным делам", l2: "lawyers", weight: 25 },
  { text: "Юрист по ДТП", l2: "lawyers", weight: 25 },
  { text: "Проверить документы при покупке дома", l2: "lawyers", weight: 30 },
  { text: "Адвокат по уголовному делу", l2: "lawyers", weight: 20 },
  // ── accountants — Бухгалтеры ──
  { text: "Услуги бухгалтера", l2: "accountants", weight: 45 },
  { text: "Заполнить налоговую декларацию", l2: "accountants", weight: 50 },
  { text: "Подать 3-НДФЛ на вычет", l2: "accountants", weight: 40 },
  { text: "Вести бухгалтерию ИП", l2: "accountants", weight: 40 },
  { text: "Сдать отчётность ИП", l2: "accountants", weight: 35 },
  { text: "Бухгалтер для ООО", l2: "accountants", weight: 25 },
  { text: "Рассчитать налоги", l2: "accountants", weight: 20 },
  { text: "Восстановить бухгалтерский учёт", l2: "accountants", weight: 15 },
  // ── documents-help — Помощь с документами ──
  { text: "Оформить документы", l2: "documents-help", weight: 40 },
  { text: "Помочь с документами в МФЦ", l2: "documents-help", weight: 35 },
  { text: "Заполнить заявление на Госуслугах", l2: "documents-help", weight: 30 },
  { text: "Зарегистрировать ИП", l2: "documents-help", weight: 40 },
  { text: "Зарегистрировать ООО", l2: "documents-help", weight: 25 },
  // спорно: может lawyers
  { text: "Оформить земельный участок", l2: "documents-help", weight: 35 },
  { text: "Получить выписку из ЕГРН", l2: "documents-help", weight: 25 },
  { text: "Помочь оформить пенсию", l2: "documents-help", weight: 30 },
  { text: "Помочь оформить пособие", l2: "documents-help", weight: 25 },
];
